- .github/ISSUE_TEMPLATE/chore.yml
- .github/ISSUE_TEMPLATE/documentation-bug.yml
- .github/ISSUE_TEMPLATE/documentation-migration-request.yml
- .github/ISSUE_TEMPLATE/documentation-request.yml
- .github/ISSUE_TEMPLATE/repo-bug.yml
This commit fixes all of the issues with the yml files now we've found how to validate them /o\
> [repo] Rename about to description

- docs/apis/plugintypes/_category_.yml
- docs/apis/plugintypes/mod.md
- general/development/policies/codingstyle/index.md
- migratedPages.js
This commit includes changes to remove lots of out-dated code, and to
point to other documentation where possible.
Fixes #21
> [docs] Migrate the Activity module docs

- docs/apis.md
- docs/apis/files/browsing.md
- docs/apis/files/index.md
- docs/apis/files/internals.md
- docs/apis/plugintypes/_category_.yml
- docs/apis/plugintypes/mod.md
- migratedPages.js
- project-words.txt
Migrated from:
https://docs.moodle.org/dev/File_API
https://docs.moodle.org/dev/File_API_internals
> [docs] api/files: Migrate file API docs

- .markdownlint.yaml
- data/migratedPages.yml
- general/development/policies/accessibility.md
- general/development/policies/codingstyle/index.md
- project-words.txt
Migrated from:
- https://docs.moodle.org/dev/Accessibility
> [docs] policies/accessibility: Migrate Accessibility docs

- docs/guides/javascript/index.md
- docs/guides/moodleapp/customisation/custom-apps.md
- docs/guides/moodleapp/development/app-in-browser.md
- docs/guides/moodleapp/development/coding-style.md
- docs/guides/moodleapp/development/development-process.md
- docs/guides/moodleapp/development/network-debug.md
- docs/guides/moodleapp/development/setup.md
- docs/guides/moodleapp/development/testing/unit-testing.md
- docs/guides/moodleapp/overview.md
- general/community/roadmap.md
- general/development/policies/component-communication/index.md
- general/development/process/peer-review.md
- general/development/process/testing/qa.md
- general/development/tools/nodejs.md
- versioned_docs/version-4.0/guides/javascript/index.md
- versioned_docs/version-4.0/tools/nodejs.md
I've been skimming through the new dev docs and I like them a lot.
I noticed that the typography is used differently and it would be maybe a good thing to use the ’ or ' consistently.
But I'm maybe too picky.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/88"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Some typography considerations.

- data/projects.json
- general/projects/docs/migration.md
- general/projects/index.mdx
- package.json
- project-words.txt
- sidebars/docs.js
- sidebars/general.js
- src/components/Person/index.d.ts
- src/components/Person/index.tsx
- src/components/Project/index.ts
- src/components/ProjectSummary/index.tsx
- src/components/ProjectSummary/styles.module.css
- src/index.ts
- static/schema/projects.json
- tsconfig.json
- yarn.lock
This set of commits is a start on the documentation of the project, and the documentation of projects in general.
This includes:
- centralised project information in JSON
- schema validation of the JSON
- sidebar generation from the JSON
- an infobox-like display of the project summary from that JSON
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/96"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] general/projects/docs/migration - Detail devdocs migration project

- general/community/intro.md
A link and a parentheses fix.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/101"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] moodle.org/dev link

- data/migratedPages.yml
- general/development/policies/security/bruteforcing-login.md
- general/development/policies/security/bufferoverruns.md
- general/development/policies/security/commandline-injection.md
- general/development/policies/security/configinfo-leakage.md
- general/development/policies/security/crosssite-request-forgery.md
- general/development/policies/security/crosssite-scripting.md
- general/development/policies/security/dataloss.md
- general/development/policies/security/dos.md
- general/development/policies/security/index.md
- general/development/policies/security/info-leakage.md
- general/development/policies/security/insecure-config.md
- general/development/policies/security/session-fixation.md
- general/development/policies/security/socialengineering.md
- general/development/policies/security/sql-injection.md
- general/development/policies/security/unauthenticated-access.md
- general/development/policies/security/unauthorised-access.md
- general/development/process.md
- project-words.txt
Migrated pages:
- https://docs.moodle.org/dev/Security
- https://docs.moodle.org/dev/Security:Unauthenticated_access
- https://docs.moodle.org/dev/Security:Unauthorised_access
- https://docs.moodle.org/dev/Security:Cross-site_request_forgery
- https://docs.moodle.org/dev/Security:Cross-site_scripting
- https://docs.moodle.org/dev/Security:SQL_injection
- https://docs.moodle.org/dev/Security:Command-line_injection
- https://docs.moodle.org/dev/Security:Data-loss
- https://docs.moodle.org/dev/Security:Confidential_information_leakage
- https://docs.moodle.org/dev/Security:Configuration_information_leakage
- https://docs.moodle.org/dev/Security:Session_fixation
- https://docs.moodle.org/dev/Security:Denial_of_service
- https://docs.moodle.org/dev/Security:Brute-forcing_login
- …
> [docs] policies/security: Migrate Security docs

- .editorconfig
- .vscode/extensions.json
See https://editorconfig.org/ for instructions to integrate with your
editor.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/109"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add EditorConfig configuration

- general/community/channels.md
- general/community/intro.md
- general/community/mission.md
- general/community/roadmap.md
- sidebars/general.js
This also fixes some minor issues with other community pages.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/115"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update chat docs to mention Matrix

- general/development/policies/security/crosssite-request-forgery.md
- general/development/policies/security/crosssite-scripting.md
Small typo and other improvements.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Small typo improvements in security pages.

- data/migratedPages.yml
- general/community/meetings.md
- general/community/meetings/202202.md
- general/community/meetings/202204.md
- general/community/meetings/202206.md
Add link to April and June meetings
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update meetings.md

- general/documentation/code-of-conduct.md
This CoC proposal has been adapted from the [Contributor Covenant](https://www.contributor-covenant.org/).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Code of Conduct proposal

- .env.default
- docusaurus.config.js
Let's make it official
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Update URL for new URL

- .github/workflows/lighthouse-report.yml
Oops.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Fix lighthouse config

- data/migratedPages.yml
- docs/apis.md
- docs/apis/plugintypes/enrol/_examples/access.php
- docs/apis/plugintypes/enrol/_examples/enrol_lang.php
- docs/apis/plugintypes/enrol/_examples/lib.php
- docs/apis/plugintypes/enrol/_examples/message_lib.php
- docs/apis/plugintypes/enrol/_examples/ui_lib.php
- docs/apis/plugintypes/enrol/index.md
- docs/apis/subsystems/access.md
- docs/apis/subsystems/enrol.md
- general/releases/1.6.md
- general/releases/1.9/1.9.3.md
- general/releases/3.1.md
Closes #26 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Enrolment plugins

- data/migratedPages.yml
- docs/apis/plugintypes/blocks/_examples/access.php
- docs/apis/plugintypes/blocks/_examples/block_pluginname.php
- docs/apis/plugintypes/blocks/_examples/edit_form.php
- docs/apis/plugintypes/blocks/_examples/pluginskel_recipe.yaml
- docs/apis/plugintypes/blocks/index.md
Closes #22 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] migrate blocks plugin page

- general/development/process/integration-review.md
Fixes #186 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix broken link, I think.

- data/migratedPages.yml
- docs/devupdate.md
- project-words.txt
- sidebars/docs.js
Migrated pages:
- https://docs.moodle.org/dev/Moodle_4.0_developer_update
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate Developer update for 4.0

- data/migratedPages.yml
- docs/apis.md
- docs/apis/subsystems/plagiarism.md
Fixes #206
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate plagiarism docs page #206

- cspell.config.js
- data/migratedPages.yml
- general/development/process.md
- general/development/tools/cibot.md
- general/development/tracker/labels.md
- project-words.txt
- sidebars/general.js
Migrated pages:
* https://docs.moodle.org/dev/Automated_code_review
Closes #177
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/209"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] development: Automated code review

- migratedPages.js
The page migration utility was using the URL slug to guess the file
name, rather than using the file name which is already available.
This change will improve the migration tooling to get these links
correct the first time.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Improve migrated page URL fixing

- general/community/roadmap.md
Reviewed the content of the Roadmap page. Testing how this works with Sara.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update roadmap

- data/migratedPages.yml
- docs/apis/plugintypes/fileconverter/_files/converter.md
- docs/apis/plugintypes/fileconverter/_files/converter.tsx
- docs/apis/plugintypes/fileconverter/index.md
- docs/apis/plugintypes/index.md
- docs/apis/subsystems/files/converter.md
- general/releases/3.3.md
Note: This change is built atop #220
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate file conversion plugins and subsystem

- data/migratedPages.yml
- docs/apis/plugintypes/index.md
- docs/apis/plugintypes/mod_data/fields.md
- docs/apis/plugintypes/mod_data/index.md
- docs/apis/plugintypes/mod_data/presets.md
Please note that this documentation needs serious love which I do not intend to provide in this edit.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/240"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate database subplugin docs

- general/community/intro.md
Updated content on the Overview page
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update overview page

- docs/apis/subsystems/files/index.md
Thanks for the sample implementation :)
fixed some minor typos
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/326"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] fixed minor typos in the sample implementation of mod_myplugin_pluginfile

- package.json
- yarn.lock
Docusaurus 2.0 is now out and we should try to keep up-to-date.
https://docusaurus.io/
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Bump to Docusaurus 2.0

- data/migratedPages.yml
- scripts/utils.js
Fixes #337 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/338"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Address issues with leading slugs

- .github/workflows/fetch-obsolete-pages.yml
- .github/workflows/label-new-issues.yml
- .github/workflows/update-moodle-metadata.yml
- .github/workflows/update-wikimedia.yml
Fixes #299
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/355"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [chore] Stop some workflows running on all clones

- general/releases/3.11/3.11.10.md
- general/releases/3.9/3.9.17.md
- general/releases/4.0/4.0.4.md
Added links to security announcements for the latest minor release.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/364"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] 404 minors: Add security fixes

- data/migratedPages.yml
- docs/apis.md
- docs/apis/core/grading/index.md
This includes two commits:
migrate the existing docs in a format as close to original as possible
update docs to suck less
I have not attempted to make these docs perfect but I think we need to just get docs migrated over ASAP now and improve quality later.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate advanced grading api

- data/migratedPages.yml
- docs/apis.md
- docs/apis/core/conditionalactivities/index.md
- docs/apis/plugintypes/availability/index.md
This includes two commits:
* migrate the existing docs in a format as close to original as possible
* update docs to suck less
I have not attempted to make these docs perfect but I think we need to just get docs migrated over ASAP now and improve quality later.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/361"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate conditional activities

- data/migratedPages.yml
- docs/apis.md
- docs/apis/core/user/index.md
This includes two commits:
* migrate the existing docs in a format as close to original as possible
* update docs to suck less
I have not attempted to make these docs perfect but I think we need to just get docs migrated over ASAP now and improve quality later.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/362"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate user API docs

- docs/apis/core/dml/index.md
Awaiting merge of https://tracker.moodle.org/browse/MDL-75170
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/366"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] core/dml: Document sql_order_by_null library method

- docs/apis/_files/db-renamedclasses-php.mdx
Additional note for the db/renamedclasses.php entry about when to add or not to add a renamed class to renamedclasses.php.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/387"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Note to clarify when to add to renamedclasses.php

- .gitignore
Add Intellij to .gitignore
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/409"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add Intellij to .gitignore

- general/development/process/testing/qa.md
- project-words.txt
Update the Moodle QA Chatroom from Telegram to the Matrix one
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix Moodle QA Chat Room

- general/community/credits/thirdpartylibs.md
- jQuery to 3.6.1
- jQuery UI to 1.13.2
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/416"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-75469 Bump jQuery versions

- docs/apis/plugintypes/format/index.md
- docs/apis/plugintypes/format/migration.md
This should be merged as soon as MDL-75771 has been integrated.
Happy to hear your feedback :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/413"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update usage of show_editor() api function

- general/community/credits/thirdpartylibs.md
* SimplePie 1.6.0 (MDL-75467)
* TCPDF 6.5.0 (MDL-75468)
* Loglevel 1.8.0 (MDL-75471)
* MaxMind 1.11.0 (MDL-75477)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/418"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Library updates for 4.1.

- docs/apis/core/activitycompletion/index.md
Just two full stops.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/423"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] main/docs/apis/core/activitycompletion/index.md

- general/community/credits/thirdpartylibs.md
> [docs] MongoDB version update to 1.13.1

- data/versions.json
- general/releases.md
- general/releases/4.1.md
Initial version of the 4.1 release notes with minimum requirements as per admin/environment.xml (with placeholders for the features/improvements to be added closer to release date as we usually do).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/435"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] 4.1 major release - added requirements and notes placeholders

- general/community/credits/thirdpartylibs.md
This PR should be merged once https://tracker.moodle.org/browse/MDL-76334 is integrated
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/439"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-76334 upgrade phpxmlrpc library to 4.8.1

- general/community/meetings/202212.md
- general/community/meetings/index.md
December Developer meeting page created with agenda and link and meeting date added in index.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Dec Dev meeting

- general/community/credits/thirdpartylibs.md
> [docs] VideoJS version update to 7.20.3

- general/releases/4.1.md
Final release notes for LMS 4.1 major release.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/451"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Complete 4.1 release notes highlights

- general/community/credits/thirdpartylibs.md
https://tracker.moodle.org/browse/MDL-75463
> [docs] Update Bennu to version 0.2

- docs/apis/commonfiles/version.php/index.md
Code area was not closed properly, affecting the parts after.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/471"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Typo and markup error

- data/migratedPages.yml
- docs/apis/_files/amd-dir.mdx
- docs/apis/_files/yui-dir.mdx
- docs/guides/javascript/ajax/index.md
- docs/guides/javascript/jquery/index.md
- docs/guides/javascript/modules.md
- docs/guides/javascript/yui/index.md
- docs/guides/templates/index.md
- general/development/tools/nodejs.md
Note: I'd like to improve this further but something is better than nothing.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate JS Modules docs

- general/development/abc/comments.md
Inspired by https://tracker.moodle.org/browse/MDL-76509
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> More on good comments

- general/community/credits/thirdpartylibs.md
Blocked by [MDL-76617](https://tracker.moodle.org/browse/MDL-76617) to land.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] mongo-php-library update to 1.15.0

- general/releases.md
3.11 end date in the past.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Update 3.11 end date

- general/development/process/security/penetration-testing.md
Fixes #441.
Inspired by wording suggested by Jonathan Champ.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Clarify wording on the sesskey token

- general/development/policies/codingstyle/index.md
As raised by @jrchamp in MDLSITE-4776.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix array cs examples

- docs/apis/subsystems/task/index.md
This should be merged only if https://tracker.moodle.org/browse/MDL-76649 is.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/512"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update task docs to cover mtrace_exception

- data/legacy-libraries.json
- data/libraries.json
https://tracker.moodle.org/browse/MDL-76219
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Replace Box/Spout with OpenSpout

- config/prism.js
- docs/apis/plugintypes/tiny/testing.md
- versioned_docs/version-4.1/apis/plugintypes/tiny/testing.md
Add some tips for writing Behat tests for TinyMCE plugins
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/514"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Tinymce Behat tips

- general/community/meetings/202301.md
- general/community/meetings/index.md
Updated index next meeting month and recording link added to January notes
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> recording link added

- general/development/policies/codingstyle/index.md
Add details about the stdClass usage based on the results of the policy issue [MDLSITE-5670](https://tracker.moodle.org/browse/MDLSITE-5670).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/545"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add more details about stdClass usage

- general/license.md
Reflects core LMS change for MDL-77376
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update our trademark statement based on latest advice from Moodle HQ Legal

- general/community/meetings/202303.md
- general/community/meetings/index.md
I've created a page for March meeting and changed the messaging in the index page.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/570"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> March developer meeting draft schedule

- general/community/meetings/202303.md
added one item to agenda
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/572"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> updated agenda

- docs/apis/subsystems/task/adhoc.md
When we wrote the task API we goofed by allowing just anyone set custom data. By setting custom data outside of the task consuming the data, we make the API harder to enforce:
* the parameters may change but we'd never find out without combing through logs
* formatting of the custom data is left to the caller
We should really encourage use of a factory to create the task itself.
I think that scheduling should still happen outside of the factory, but the user configuration also belongs in the factory.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/590"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: Add guidance on setting custom task data and user

- general/development/tools/behat/writing.md
That's the second to last title.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/599"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove superfluous line

- docs/apis/subsystems/xapi/index.md
In [MDL-67789](https://tracker.moodle.org/browse/MDL-67789), support to xAPI state was added to core_xapi and used in mod_h5pactivity to store the content state for each user. This page has been updated properly to include the xAPI state changes implemented in Moodle.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/593"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add xAPI state information

- general/releases/4.2.md
Fixes #550.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/606"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add Moodle 4.2 release note skeleton

- general/community/credits/testing.md
As part of the release process we need to add the list of QA testers
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/609"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add 4.2 QA cycle testers

- docusaurus.config.js
Configuration and suggestion by @moodler-zz.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/618"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add integration with zipchat

- data/migratedPages.yml
- docs/guides/profiling/index.md
- general/development/gettingstarted.md
https://docs.moodle.org/dev/Profiling_PHP
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate the Profiling documentation

- data/migratedPages.yml
- docs/guides/javascript/modal/index.md
- general/releases/3.2.md
- versioned_docs/version-4.1/guides/javascript/modal/index.md
- versioned_docs/version-4.2/guides/javascript/modal/index.md
Docs for Moodle Modals.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Modal docs

- data/migratedPages.yml
- general/development/tools/composer.md
- general/releases/3.2.md
Migrate https://docs.moodle.org/dev/Composer
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/638"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate Composer page

- docs/devupdate.md
- docs/guides/javascript/modal/index.md
MDL-78306
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78306 - Modal esm conversion

- general/development/policies/php.md
It was decided finally some weeks ago, so let's write it down there.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/668"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Setup the agreement about php82 being for both 4.2.x and 4.3

- docs/devupdate.md
A few minor updates to the devupdate page for 4.3.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/666"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Dev update improvements

- src/css/custom.css
Closes #715.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/722"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [site] Update style for nested ordered lists to auto

- data/component-spelling.txt
- docs/apis/subsystems/enrol.md
- docs/devupdate.md
Changes of MDL-78855 documented
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Enrol plugin API update related to csv course upload

- general/development/policies/deprecation.md
This is to solve issues identified and raised in MDLSITE-7358
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update deprecation policy for named argument support

- docs/devupdate.md
To document changes done in https://tracker.moodle.org/browse/MDL-78993
> [docs] Removed $CFG->svgicons setting

- general/projects/api/string-deprecation.md
As spotted by Paul https://tracker.moodle.org/browse/MDL-79616?focusedCommentId=1034634&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1034634
> Removing double negative

- general/releases/3.11/3.11.17.md
- general/releases/3.9/3.9.24.md
- general/releases/4.0/4.0.11.md
- general/releases/4.1/4.1.6.md
- general/releases/4.2/4.2.3.md
I won't be logging back in until next week, so if you spot any errors, please feel free to update!
> [docs] Updates for 4.2.3 minor release

- general/community/credits/testing.md
- general/development/process/testing/qa.md
As part of the QA cycle wrap up we need to update the list of testers credits
> Add testers of 4.3 QA cycle.

- data/versions.json
This updates all of the minor and major versions for the next three months.
> Update the most recent version numbers.

- docs/apis/plugintypes/enrol/index.md
- docs/devupdate.md
> Mutliple enrol instance in csv course upload

- general/community/plugincontribution/pluginsdirectory/updates.md
Lastest updates on the Plugins Directory
> [doc] Update about Plugins directory pagination

- general/development/tools/phpcs.md
until there is a stable version of phpcompatibility that we can require
> added necessary step to composer installation

- general/releases.md
Info requested in https://moodle.org/mod/forum/discuss.php?d=452089
If there's a better place on the page for the info, please move it. ;-)
> Add note about next LTS version

- general/community/plugincontribution/pluginsdirectory/updates.md
I have added the latest modifications that were deployed to the plugins directory.
> [docs] News in the plugins directory updates page

- docs/guides/git/index.md
- general/community/plugincontribution/master2main.md
This page has been created using the information in Eloy's gist: https://gist.github.com/stronk7/d007be57062ebef2dd6549010954a378
Although my first idea was to add it to  Coding > Advice, I finally decided it fits better into the Community > Plugin contribution section :-) 
Thanks for creating this useful information, @stronk7 :-*
> [docs] Master to main documentation

- docs/apis/plugintypes/atto/_examples/button.tsx
- versioned_docs/version-4.2/apis/plugintypes/atto/_examples/button.tsx
- versioned_docs/version-4.3/apis/plugintypes/atto/_examples/button.tsx
> [docs] Correct atto example filetype

- docs/devupdate.md
Added subsections into the BS5 section to help to easily find information.
> [docs] Dev update BS5 reorganization

- general/community/plugincontribution/checklist.md
Adding section of text requested by Chris Brown/
I think this is the right place for it, happy for suggestions to change.
> [docs] Add intellectual property rights section

- docs/apis/_files/db-upgrade-php.tsx
Example code was missing required return statement.
> Add missing return statement

- general/development/policies/accessibility.md
* Add WCAG 2.1 Level AA accreditation date for 4.1/4.2
* Update the accessibility tools section to reflect the latest tools used for testing accessibility.
> Update accessibility page

- general/community/meetings/202402.md
Update to add my presentation URL.
Thanks,
> Add Feb 2024 Developer meeting presentation URL

- docs/apis/core/hooks/index.md
- docs/devupdate.md
> [docs] Add docs for attribute_helper and attribute-described hooks

- docs/apis/core/hooks/index.md
While implementing my first hook I stumbled over these - IMO - errors on the hook API page.
> Fix some errors on hooks api page

- general/documentation/contributing.md
Note - need to wait for the preview to render to know if this worked.
> Add information about Mermaid to contributing.md

- data/versions.json
- docs/intro.md
- general/releases.md
- general/releases/4.4.md
> [docs] Add release meta-data for Moodle 4.4

- docs/apis/subsystems/task/index.md
- docs/devupdate.md
Note: This is blocked by #950 and [MDL-67667](https://tracker.moodle.org/browse/MDL-67667)
> [docs] Document removal of blocking task support - MDL-67667

- general/community/credits/testing.md
As part of the release process we must give credits to all our QA testers
> 4.4 QA cycle credits

- general/development/process/testing/qa.md
Add the 4.4 QA cycle link to the list of QA previous cycles.
> Link to 4.4 QA cycle

- docs/apis/subsystems/task/adhoc.md
- docs/devupdate.md
Add Task APIs (No-retry and maximum attempts) for MDL-79128
> Add new Task APIs documentation

- docs/devupdate.md
- docs/guides/javascript/index.md
Add `core/dropzone` documentation in MDL-80850
> Add dropzone documentation

- docs/apis/subsystems/form/fields/_category_.yml
- docs/apis/subsystems/form/fields/choicedropdown.md
- docs/apis/subsystems/form/index.md
Add description on how to use the choicedropdown form field.
> [docs] Describe choicedropdown form field

- general/development/tools/generator.md
- project-words.txt
Just some minor fixups including:
- removing unnecessary new lines to make readability of future diffs better
- moving jmeter into project-words cspell list
- move important note to an important admonition
- some minor simplifications of a few sentences.
> [docs] Tidy up the Generator UI docs

- data/migratedPages.yml
- general/development/process/testing/qa.md
Migrate interesting content from https://docs.moodle.org/dev/Acceptance_testing/Contributing_automated_tests into existing https://moodledev.io/general/development/process/testing/qa
> [general] Migrate Acceptance_testing/Contributing_automated_tests

- general/development/process/release/index.md
- general/documentation/forking-versions.md
Note: Once #1006 lands I'll update the references to the example commits and submit this PR.
> Version fork docs

- .markdownlint-cli2.cjs
- data/versions.json
- docs/intro.md
- src/components/ReleaseStateSummary/index.tsx
- src/utils/SupportedReleases.ts
- static/schema/versions.json
- versioned_docs/version-4.1/intro.md
- versioned_docs/version-4.2/intro.md
- versioned_docs/version-4.3/intro.md
- versioned_docs/version-4.4/intro.md
Fixes #1017 
Note: I think we should add additional data here, including:
- next minor date
- supported PHP versions
- link to issue deciding requirements
Those are for the future.
> Add useful information about code freeze and other key dates.

- general/development/tools/nodejs.md
> Fixing typo in npx command

- docs/devupdate.md
https://tracker.moodle.org/browse/MDL-81572
> TinyMCE plugin lang string developer update (4.5).

- docs/devupdate.md
> [docs] Note move of autoloader in Moodle bootstrap process

- docs/apis/subsystems/time/index.md
> [docs] Document \core\clock in more places

- general/community/meetings/2024/05.md
- general/community/meetings/index.md
This is a pull-request to fix a couple of minor things raised in https://github.com/moodle/devdocs/pull/1042
> [general] Amend presentation link and list May meeting in the index

- docs/guides/bs5migration/index.md
This PR contains documentation for [MDL-81818](https://tracker.moodle.org/browse/MDL-81818)
> [docs] Documentation for MDL-81818

- docs/devupdate.md
Adding documentation on the developer notes page for https://tracker.moodle.org/browse/MDL-82160
> [docs] Documentation for MDL-82160

- general/development/tools/generator.md
In MDL-81886, the make testing scenario tool is able to execute outline scenarios, not just regular ones.
> [docs] Documentation for MDL-81668

- general/development/policies/accessibility.md
Update accessibility page for Moodle Workplace 
Fixes https://tracker.moodle.org/browse/WP-4964
> WP-4964 Update Accessibility page for Moodle Workplace

- docs/devupdate.md
- docs/guides/bs5migration/index.md
This PR is blocked and needs to land after https://github.com/moodle/devdocs/pull/1035
This PR is related to https://tracker.moodle.org/browse/MDL-81819
> [docs] Documentation for MDL-81819

- docs/apis/subsystems/output/index.md
[MDL-70854](https://tracker.moodle.org/browse/MDL-70854)
> MDL-70854: Add docs for progress_bar and stored_progress_bar.

- docs/apis/_files/db-legacyclasses-php.mdx
- docs/apis/_files/db-legacyclasses-php.tsx
- docs/apis/_files/index.tsx
- docs/apis/commonfiles/index.mdx
- docs/devupdate.md
- project-words.txt
> [docs] Document use of legacyclasses.php

- general/development/policies/accessibility.md
- Add WP Accessibility Accreditation link and date to the Accessibility page in dev docs
> WP-5017 Add WP Accessibility Accreditation link

- docs/guides/bs5migration/index.md
This PR is blocked and needs to land after https://github.com/moodle/devdocs/pull/1035
This PR is related to https://tracker.moodle.org/browse/MDL-75671
> [docs] Documentation for MDL-75671

- general/development/tools/generator.md
> [docs] tool generator available steps list information

- general/community/meetings/2024/09.md
- general/community/meetings/index.md
Pending update date and agenda (@wildgirl will do) ;-)
> [general] Add September 2024 meeting

- data/versions.json
- scripts/version.mjs
This commit adds the following changes:
- a new version management script to make modifying the versions.json far easier
- a fix for some 1.9 version data
- the next set of release information for each branch
> Next release

- general/community/meetings/2024/11.md
- general/community/meetings/index.md
This is a proposal with the agenda for the next Moodle developer meeting agenda :-)
> [general] Create November 2024 meeting

- docs/apis/subsystems/ai/index.md
- versioned_docs/version-4.5/apis/subsystems/ai/index.md
This PR is created as a part of MDL-83403.
> Updating docs AI subsystem

- general/releases.md
Not much to say, just those dates have already passed.
> A few dates are now in the past (April and October 2024)

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-81823
> [docs] Documentation for MDL-81823

- docs/apis/plugintypes/ai/index.md
- docs/apis/plugintypes/ai/placement.md
- docs/apis/plugintypes/ai/provider.md
- versioned_docs/version-4.5/apis/plugintypes/ai/index.md
- versioned_docs/version-4.5/apis/plugintypes/ai/placement.md
- versioned_docs/version-4.5/apis/plugintypes/ai/provider.md
Documentation updates for MDL-83402. It has already been peer reviewed at this stage. Check tracker issue for more details.
> [docs] AI: Update AI documentation (MDL-83402)

- general/development/abc.md
- general/development/abc/fixups.md
I hope this is a useful contributions.
It is a page I often wish existed when I am doing peer reviews and CLRs, so finally, I made time to write it.
Suggestions for improving this welcome. Merry Christmas. 🎅
> Add an ABC page about using fixup commits and branches

- general/community/meetings/2025/01.md
Added the slides I used in the presentation
> Heikki's slides

- docs/apis/plugintypes/format/index.md
Add more information about state updates and the non-ajax alternative to execute them in Moodle 5.0.
> MDL-82767 course format state updates

- general/development/policies/moodle-versions.md
@cameron1729  pointed out that we don't actually have this documented anywhere in docs, just in a tracker issue.
> Moodle version dependency requirements

- docs/apis/plugintypes/mod/courseoverview.md
This is the extra documentation for the activity overview grade item introduced in MDL-83888.
> MDL-83888 Activity overview redirection

- docs/apis/plugintypes/mod/courseoverview.md
- docs/apis/subsystems/output/index.md
This pull request is related to the patch on [MDL-83888](https://tracker.moodle.org/browse/MDL-83888).
> MDL-83888 new overview redirection and renderer helper

- docs/apis/subsystems/sms/index.md
Documentation related to [MDL-84342](https://tracker.moodle.org/browse/MDL-84342)
> MDL-84342 Add message truncation

- general/community/meetings/2025/03.md
Add time-stamps into the recording of the March 2025 dev meeting.
> Meeting recording time-stamps

- general/contentguidelines/01-productwriting/contentprinciples.md
- general/contentguidelines/02-styleguide/grammar.md
- general/contentguidelines/02-styleguide/index.md
I have updated our content principles so they match our content design practice, and moved some of the things to Grammar. I have updated Grammar too to make the content clearer, and changed the short intro in the index page.
> [Docs] Updating content principles and grammar, and index

- general/community/credits/moodleorg.md
Added a few missing moderators and updated the list. Long overdue.
> Update moodleorg.md moderator's list updated 

- general/community/credits/moodleorg.md
> Update moodleorg.md unlinked hidden courses

- config/footer.js
Adding link to Accessibility statement and updating link to X.
> Adding Accessibility statement

- general/community/contribute.md
Removing mention of MUA and adding Fund Moodle, as suggested in MDLSITE-8092.
> Updating how to maximize the chance of your idea being implemented

- docs/guides/javascript/reactive/index.md
- versioned_docs/version-4.1/guides/javascript/reactive/index.md
- versioned_docs/version-4.4/guides/javascript/reactive/index.md
- versioned_docs/version-4.5/guides/javascript/reactive/index.md
- versioned_docs/version-5.0/guides/javascript/reactive/index.md
> [repo] Fix typo in reactive index.md

- general/releases/4.4.md
- general/releases/4.5.md
- general/releases/5.0.md
- general/releases/5.1.md
- general/releases/5.2.md
- general/releases/5.3.md
This addresses the concerns of [MDL-85485](https://moodle.atlassian.net/browse/MDL-85485) without requiring a code change, by documenting the known reserved word issue with MySQL 8.0.0.
[MDL-85485]: https://moodle.atlassian.net/browse/MDL-85485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [docs] Add additional info to MySQL required version
