moodle/devdocs

- docs/apis.md
- docs/guides/moodleapp/coding-style.md
- general/development/process.md
- migratedPages.js
- src/remark/legacyDocLinks.js
The commit adds a new migratedPages.js module which includes a list of
legacy page to new page mappings.
When a legacy link in the Wikimedia internal link format is encountered,
it is checked against this list of migrated pages, and an updated page
URL is generated.
This value is notified to the Docusaurus CLI console, and the updated
link is used in the generated documentation.
> [system] Keep track of migrated docs and warn on use

- academyCourses.js
- docs/apis/access.md
- package.json
- src/components.js
- src/components/AcademyLink.js
- yarn.lock
This is part of a change to introduce standard links to courses on
Moodle Academy.
We create a single canonical list of courses in `/academyCourses.js`,
a custom Admonition via a JSX component, and a custom page listing all
academy courses relevant to Development.
That component can take properties to describe:
- the topic being taught
- a short name for the course
- possibly further information to include
The list of courses in academyCourses.js has a list of the courses, with
their shortname as an object key, and then relevant metadata, including:
- The course full name
- The course link or id
- A summary to be used in a tooltip
- A full description to be used in the course list page
- information as to whether the course has been archived
- tags
- icon
The academyCourses page also uses …
> Link to courses on the Moodle Academy

- .gitpod.yml
- README.md
Add a `.gitpod.yml` configuration to allow for really quick in-browser changes and checking of PRs.
<a href="https://gitpod.io/#https://github.com/andrewnicols/dinodevdocs/pull/42"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add gitpod configuration for in-browser demo

- data/migratedPages.yml
- general/development/process.md
- general/development/process/peer-review.md
- general/development/process/testing.md
- general/development/process/testing/guide.md
- general/development/process/testing/integrated-issues.md
- general/development/process/testing/qa.md
- sidebars/general.js
This patch migrates https://docs.moodle.org/dev/Testing_instructions_guide page (I've used the script in https://github.com/moodle/devdocs/pull/63 for migrating it) <3
> [docs] process/testing/guide: Migrate testing instructions guide

- .github/workflows/update-wikimedia.yml
Before it only ran if we pushed directly to main without a pull request.
We should be comparing the `github.repository`, documented at
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
to the canonical repository.
> [repo] Correct expression to only run on moodle/devdocs

- general/development/process/testing/qa.md
As discussed in https://github.com/moodle/devdocs/issues/41, it has
been agreed to remove references to Contact to Helen in QA testing
page. These changes has been done in https://docs.moodle.org/dev/QA_testing
and this commit is to remove also from the new page.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/72"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove references to contact Helen in QA

- general/development/process/triage.md
These two pages landed at the same time in different issues and I didn't
spot them when merging.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/79"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] general: Fix migrated page

- package.json
- scripts/utils.js
- scripts/wikimedia-fetch.js
- src/lib/legacyDocLinks.js
- src/remark/legacyDocLinks.js
- yarn.lock
This is a really basic system to fetch a page from the legacy docs into
a new location on disk, and perform basic changes.
It does *NOT* catch everything and it can do better, but it's what I've
been doing manually.
At the moment it will:
- not convert any table
- complain about migrated pages but not fix them
- do nothing with tracker links
- not update the migratedDocs.yml file with it's existence
I've tried to merge some of the functions and utilities that I
previously wrote for the legacy wiki updater into a shared utils file
too.
Usage:
```
node scripts/fetchLegacyPage.js migrate [Legacy_Page_Title] [path/to/new/page.md]
```
> [repo] Create a basic fetch script

- .stylelintrc.json
- package.json
- src/components/HomepageFeatures/index.js
- src/components/HomepageFeatures/styles.module.css
- src/css/custom.css
- src/pages/index.js
- src/pages/index.module.css
- yarn.lock
I discovered whilst working on another issue that I'd missed checking in
the stylelint configuration.
This makes use of `stylelint-config-standard`, which should cover most
of our usage.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/95"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add stylelint configuration

- .lintstagedrc.json
Markdown lint should be able to check mdx files too.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/98"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Ensure that mdx files are linted too

- cspell.config.js
The cspell config file is not declaring the new Moodle dictionaries for components and contributors.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix cspell config

- .stylelintrc.json
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
This workspace configuration includes recommendations for the following
extensions:
- davidanson.vscode-markdownlint - Markdown Linting
- streetsidesoftware.code-spell-checker = Official cspell integration
- dbaeumer.vscode-eslint - Official Microsoft eslint integration
- tberman.json-schema-validator - JSON Schema validation
- silvenon.mdx - MDX syntax highlighter
- gamunu.vscode-yarn - Yarn integration
A second commit also configures stylelint configuration for the workspace.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Include vscode workspace config

- .lintstagedrc.json
The markdown lint is not aware enough of MDX, and some of the properties
will regularly fail cspell.
We'll try this again later.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/112"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Stop linting mdx files for now

- general/development/policies/codingstyle/index.md
There's no need for an asterisk there in the
A "de-facto Moodle standard"* is any coding style which is commonly and typically used in Moodle.
sentence.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] remove unnecessary asterisk.

- docs/_utils.tsx
- docs/apis/_files/version-php.tsx
- src/components/ComponentFileSummary.tsx
- src/moodleBridge.tsx
The description needs to benormalised because it can be any of:
- string
- React.Fragment
- MDXContent
The MDXContent had me puzzled for a bit. It isn't a standard React
component. We need to put it in an MDXProvider to put it into a
component.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Address some syntax issues with the ComponentFileSummary

- package.json
- scripts/utils.js
- scripts/wikimedia-sync.js
- yarn.lock
This commit updates our package config to use the latest version of [nodemw](https://github.com/macbre/nodemw) which adds support for protecting page (which I wrote).
The patch then adds protection for all migrated pages.
I have now added a (crappy looking) banner to the old pages linking to the new. Locking those pages prevents most people from changing them. We do still need to keep an eye on them (and maybe we can automate this better too) as admins can still make changes. We also have a few which have been updated since we migrated and need to check those and update the new docs too.
> [repo] Automatically protect migrated pages

- package.json
- yarn.lock
This includes a bug fix for the nodemw getArticleInfo function we use to lock pages.
> [repo] Bump version of nodemw for articleInfo fix

- docs/gettingstarted/requirements.md
Some links which were broken with the lint fix recently.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] docs/gettingstarted: Fix broken links

- docusaurus.config.js
When we moved the repo, I missed one of the editUrls
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Fix editUrl for general

- general/documentation/contributing.md
This commit adds some links to the GitHub edit UI docs, and pull request docs.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add links to GitHub docs on editing

- package.json
This patch fixes the mdlint-all (so `yarn mdlint-all` should work) and also add migrate to the scripts list, to run it easily:
`yarn migrate WIKIMEDIAPAGE docusaurusfolder/file.md -i`
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Fix mdlint-all and add migrate

- scripts/wikimedia-sync.js
Just useful to be able to help us identify which pages to migrate.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Generate a list of pages left to migrate

- data/migratedPages.yml
The link to the migrated Moodle Developer Resources on this page https://docs.moodle.org/dev/File_API in MediaWiki is broken. It's currently pointing to https://moodle.github.io/devdocs/docs/subsystems/apis/files but the correct link would be https://moodle.github.io/devdocs/docs/apis/subsystems/files.
See: https://github.com/moodle/devdocs/issues/58#issuecomment-1135016043
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Fix link from old docs to new docs for File API

- UPGRADING.md
- docusaurus.config.js
- general/community/intro.md
- general/development/index.md
- general/documentation/code-of-conduct.md
- general/documentation/index.md
- package.json
- yarn.lock
This series of commits migrates us from Docusaurus 2.0.0-beta-18 to 2.0.0-beta-21.
It also includes documentation on how to perform this upgrade.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/158"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Upgrade to Docusaurus 2.0.0-beta.21

- data/migratedPages.yml
- docs/apis/_files/index.tsx
- docs/apis/_files/upgrade-txt.mdx
- docs/apis/_files/upgrade-txt.tsx
- docs/apis/commonfiles/index.mdx
Migrated page:
- https://docs.moodle.org/dev/Upgrade_notes
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrade Upgrade notes page

- .github/workflows/lighthouse-report.yml
- .github/workflows/lighthouserc.json
- scripts/format-lighthouse-score.mjs
This is borrowed from Docusaurus upstream and retains their copyright.
This change adds a lighthouse report for several key pages to pull requests to help us keep an eye out for possible issues.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add lighthouse report

- .github/workflows/lighthouse-report.yml
I had these URIs in my editor and had not saved them. These replace the
ones 'borrowed' from Docusaurus.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] And use the URIs that I selected

- .github/workflows/lighthouse-report.yml
The previous copy of wait-for-netlify is only looking for any build, not for a specific build. That meant that subsequent pushes to the branch on the same pull request immediately return the previous Netlify build, and the lighthouse report related to that build.
This change also updates the Lighthouse report to run against the permalink for the build rather than the Deploy preview. The difference is that the permalink is the pure build as it would be against on the live site, whilst the deploy preview includes a bottom banner for Netlify with some useful tools. This negatively affects the performance scores for Lighthouse and brings up some false issues.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Switch to commit-specific wait-for-netlify alternative

- .github/ISSUE_TEMPLATE/system-bug.yml
@timhunt would you like to review this?
I did look at other renames, but they already seem to be appropriate.
The other thought I had was to sort the templates so that there is a more appropriate sorting on the New issue screen (for example `06-chore.yml` to put the Chore/Maintenance item last).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/197"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Update system bug issue template

- config/navbar.js
The Versions dropdown is not in use at the moment until we fork the docs for 4.1 (when we hit enough items), and the Github links is not helpful right now.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Remove unused navbar items

- src/css/custom.css
This means that, on wider screens, the 'Edit this page' link is always
visible.
I've tried to keep it relatively small and out-of-the way so as not to
detract from content or take up too much space.
I dare say we can improve this in the future, and when we get it working
nicely it would be good to release it as a separate docusaurus plugin.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Modify the doc footer to float

- config/navbar.js
- docs/apis/_files/db-services-php.mdx
- docs/apis/plugintypes/antivirus/index.mdx
- docs/apis/plugintypes/blocks/index.md
- docs/apis/plugintypes/format/migration.md
- docs/apis/plugintypes/qbank/index.md
- docs/apis/subsystems/analytics/index.md
- docs/apis/subsystems/files/index.md
- docs/guides.md
- docs/intro.md
- sidebars/docs.js
- src/css/custom.css
This changes adds a new guides landing page for the non-API guides, and
updates the main landing page for the version-specific documentation.
I've also removed the link to the 'Getting started' from the sidebar
because it takes you away from the API information and changes the
sidebar navigation completely, which makes it harder to go back to the
previous area.
As part of this I've also restructured the sidebar to move the Developer
update notes to the top section above the break, so that all
documentation for the version is together, in one place.
> [docs] docs: Tidy up the Guides landing

- general/community/meetings/202206.md
Thanks to Andrew for suggesting using a direct link to the recording.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use direct link to recording

- docs/apis/plugintypes/index.md
- docs/apis/plugintypes/logstore/index.md
- docs/apis/plugintypes/mod_book/index.md
- docs/apis/plugintypes/mod_forum/index.md
- docs/apis/plugintypes/tinymce/index.md
These are just placeholders. These docs don't exist right now.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate undocumented plugintypes

- scripts/utils.js
When we started marking pages as protected we should have also set the template addition as a major change and not a minor change.
> [repo] Noting a page as migrated is a major edit

- docs/guides/javascript/reactive/index.md
The available update types section is missing the "remove" state update.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/290"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add remove state update to reactive

- data/migratedPages.yml
- general/development/policies/php.md
- general/releases/3.10.md
- general/releases/3.11.md
- general/releases/3.5.md
- general/releases/3.6.md
- general/releases/3.7.md
- general/releases/3.8.md
- general/releases/3.9.md
- general/releases/4.0.md
This migrates the https://docs.moodle.org/dev/Moodle_and_PHP
page to devdocs/general/development/php and, given php80
support has been officially announced for 3.11 and 4.0,
amend the release notes of those versions to tell so.
Then, register it as migrated page.
And finally, fix all the links to the old page (`yarn mdfix-all`).
Let's see if everything is in place (`yarn build` said ok), yay!
Ciao :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate the "Moodle and PHP" page and related changes

- general/releases/3.11/3.11.8.md
- general/releases/3.9/3.9.15.md
- general/releases/4.0/4.0.2.md
In the future, perhaps it would be better to just note the planned release date when drafting the new release notes for the next minors. People should be able to determine the actual release status of the version from the indicated release date, right?
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update release dates on the release notes

- package.json
- project-words.txt
- scripts/wikimedia-fetch.js
This pair of commit adds `yarn fix` as a shortcut to `yarn mdfix-all; yarn mdxfix-all; yarn spell` to perform standard checks for all files.
It then also updates the `yarn migrate` command to use the new command, and makes it run _after_  we add to `migratedPages.yml` which makes it actually useful in that instance.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/280"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Make yarn fix to call to common fixes

- src/theme/UnsupportedVersionBanner/index.js
Create an unreleased title to display for future versions instead of using the unsupported one.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/306"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Unreleased title for versions

- general/releases/3.11/3.11.8.md
- general/releases/3.9/3.9.15.md
- general/releases/4.0/4.0.2.md
Added security fixes for latest minor release. Also removed links to translations that did not correspond to the relevant page (versions corresponding with these releases did not appear to exist to replaced them with), and added the one 4.0.2 translation page that did exist in the old docs (FR).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] 402 minors: Add security fixes and remove incorrect translations

- docs/apis/core/dml/delegated-transactions.md
This removes two points from the general principles section that
were not useful.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] dml: Transaction page removal of two points.

- general/development/policies/codingstyle/index.md
Added the naming convention for web service functions in the Coding style.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add naming convention for web service functions

- data/migratedPages.yml
- docs/apis/subsystems/form/advanced/checkbox-controller.md
- docs/apis/subsystems/form/advanced/no-submit-button.md
This small patch just migrates two more of the advanced form features.
There are still a couple of form-related pages to migrate but these are non-trivial and I'll do them as separate PRs due to their size.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate form features

- data/migratedPages.yml
- docs/apis.md
- docs/apis/_files/lang.tsx
- docs/apis/plugintypes/availability/_examples/lang.md
- docs/apis/plugintypes/availability/_examples/lang.php
- docs/apis/plugintypes/availability/index.md
- docs/apis/plugintypes/index.md
- docs/apis/subsystems/access.md
- docs/apis/subsystems/availability/index.md
- general/releases/2.7.md
Note: This change does _not_ migrate the https://docs.moodle.org/dev/Conditional_activities_API page because it is not clear what the purpose of this is and whether it should be merged into other locations or not.
I'll speak with @sammarshall_ou about this and will handle it as a separate PR.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/309"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate Availability subsystem

- docs/apis/plugintypes/mod/index.mdx
Should fix https://github.com/moodle/devdocs/issues/320 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/322"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove reference to NEWMODULE Documentation

- general/development/policies/deprecation.md
Add a mention to corresponding upgrade.txt documenting the deprecated PARAMETER should not be used any more.
instead of
Add a mention to corresponding upgrade.txt documenting the deprecated method should not be used any more.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fixing an error on deprecating a parameter doc

- general/development/policies/deprecation.md
In MDLSITE-6729 (policy issue), an agreement was done to add more information for initial and final class deprecation.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add agreement for the class deprecation

- docs/apis/subsystems/output.md
I removed "The following documentation is also related", because it is covered by the "See Also" section.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Output API - Fix typos and grammar

- general/releases/3.11/3.11.9.md
- general/releases/3.9/3.9.16.md
- general/releases/4.0/4.0.3.md
Pull request to publish security announcements as part of the minor release +1 week process.
Also added a security improvement item to document a previous security fix that was re-implemented this release to eliminate a regression from the original patch.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] 403 minors: Add security fixes and improvements

- docs/apis/commonfiles/version.php/index.md
https://docs.moodle.org/dev/version.php had some rules around the YYYYMMDDXX version number for plugins in stable branches. This patch just adds that back.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/346"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Re-add section from the old version of this page

- general/development/process/testing/guide.md
I've seen many instances of people writing testing instruction with steps like "Enable redis" or something similar. It would be nice if the guidelines explicitly state that this is not an ideal way to write testing instructions.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/345"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add guidelines for writing testing instructions to enable features (plugins, settings, etc)

- data/migratedPages.yml
I imagine this is the cause for the old docs pointing to incorrect URL in the new docs. AKA:
https://docs.moodle.org/dev/Moodle_and_PHP
is pointing to:
https://moodledev.io/general/development/php
and it should point to:
https://moodledev.io/general/development/policies/php
It seems that in the last move of that page, the information was modified only partially.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/354"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix incorrect slug

- docs/apis/subsystems/access.md
- general/development/policies/deprecation.md
This branch documents the technical process for deprecating a capability, as implemented by MDL-55580.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/367"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-55580 Document capabilities deprecation

- data/migratedPages.yml
- docs/apis.md
- docs/apis/core/activitycompletion/index.md
This includes two commits:
* migrate the existing docs in a format as close to original as possible
* update docs to suck less
I have not attempted to make these docs perfect but I think we need to just get docs migrated over ASAP now and improve quality later.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/358"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate Activity completion API docs

- general/documentation/contributing.md
Changed to the correct link for the Docusaurus homepage
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/373"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  [docs] Fix Docusaurus link

- general/releases/3.11/3.11.9.md
- general/releases/3.9/3.9.16.md
- general/releases/4.0/4.0.3.md
Additional security fix for the August release which was omitted in the original announcements.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] 403 release: Added additional security fix

- data/migratedPages.yml
- general/license.md
- static/_redirects
This includes a redirect for /license
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate License documentation

- general/development/policies/codingstyle-moodleapp.md
- src/components.js
- src/components/CodeExample/index.js
- src/components/CodeExample/styles.module.css
- src/components/ValidExample/index.js
Other than migrating the app coding style, I've also refactored a couple of the components to use them in the code examples.
I've done the following:
- Extracted common parts of `ValidExample` and `InvalidExample` in to `CodeExample`.
- Added new optional parameters to specify type (success, warning, info, etc.) and title.
- Added some margin below the title and removed the one below the code block.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate app coding style

- general/development/process/release/index.md
Add a point to -4w before release (1w after freeze) about to bump the priority of all the minor/trivial non-bug issues to major.
This includes both must-fix issues and issues already under IR/CLR which unique affected version is the one to be released. (the query needs to be amended on every release, it's noted in the new step description).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/398"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump the priority of non-bugs related with the release

- general/documentation/installation.md
When digging through the docs, I found a small typo in the link to Docusaurus. Should be a fast merge. :)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/410"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix small typo in the Docusaurus link

- data/migratedPages.yml
- general/development/abc/faq.md
- general/development/gettingstarted.md
I have removed a few chunks which related to older Moodle 2.0 implementation. I have also removed the section regarding 'HEAD' as I believe this to be ubiquitous with Moodle development these days. I updated a lot of outdated and redirecting links to their current counterparts. I added in a section about downloading Moodle. I also embellished on some sections to give them more meat.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/411"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate Developer FAQ

- general/community/credits/thirdpartylibs.md
See: https://tracker.moodle.org/browse/MDL-75466
This also harmonizes the links to https://github.com/PHPMailer/PHPMailer.
http://phpmailer.sourceforge.net redirects to https://phpmailer2.com/, which seems to be a different project (see: https://phpmailer2.com/index.php?pg=history)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/421"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-75466 upgrade PHPMailer to 6.6.5

- general/community/credits/thirdpartylibs.md
**IMPORTANT NOTE**: This only should be merged if/when [MDL-76055](https://tracker.moodle.org/browse/MDL-76055), that introduces it, is successfully integrated.
This adds the new phpxmlrpc library from MDL-76055 to the documentation. A php-only replacement for the xmlrpc extension (deprecated since php80).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add lib/phpxmlrpc to the thirdpartylibs

- general/community/credits/thirdpartylibs.md
This PR should be merged once https://tracker.moodle.org/browse/MDL-73853 will be integrated (this is the issue to upgrade both H5P libraries, core and editor) :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/422"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Upgrade H5P core and editor libraries to moodle-1.22.4

- general/releases/4.0/4.0.5.md
We don't want additional bugs (amended in tracker, too).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/429"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Typo: BugBlueButton instead of BigBlueButton

- data/versions.json
Must be 14 November 2022 instead of 14 October 2022
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/430"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix 4.0.5 and friends release date

- general/releases/3.11/3.11.11.md
- general/releases/3.9/3.9.18.md
- general/releases/4.0/4.0.5.md
- general/releases/4.1.md
Security announcements for release +1 week.
Also included an extra commit to fix a couple of missing para spaces in the 4.1 requirements notes.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/444"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor release security fixes and 4.1 small fix

- docs/guides/templates/index.md
I spent a good while trying to debug why my variables weren't able to be rendered until I realised I had variables name clashes with core template helper methods.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/443"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added note regarding variable naming

- scripts/utils.js
- scripts/wikimedia-sync.js
When marking a page as migrated in Wikimedia we should clear the page content. It's time we started to clear out the old site!
> [repo] Clear the content of migrated pages on wikimedia

- general/development/process/peer-review.md
Because I'm drafting something similar for Workplace, and want to use these docs as reference (avoiding me having to add the links in our documentation, better to send upstream)
> Link to appropriate docs from review checklist.

- sidebars/docs.js
The current "Release notes" link in the sidebar menu in Guides is still pointing to 4.0. This patch updates the link to 4.1.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Point to the latest release

- data/versions.json
Added date information for the 4.2 release
- Release date: 24 April 2023
- General support end date: 22 April 2024 (Monday on its 12th month)
- Security support end date: 21 October 2024 (Monday on its 18th month)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add date data for the 4.2 release

- data/migratedPages.yml
- docs/apis/_files/yui-dir.mdx
- docs/guides/javascript/yui/index.md
- docs/guides/javascript/yui/modules.md
- docs/guides/javascript/yui/namespacing.md
This series of commits migrates any YUI docs which are still relevant. Whilst we do not encourage any _new_ YUI development, we do still need to maintain what we have for the next few years.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/466"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate various YUI docs

- data/migratedPages.yml
- docs/guides/javascript/ajax/index.md
- general/releases/1.7.md
- general/releases/2.9.md
- general/releases/3.0.md
This patchset migrates the current ajax docs, then rips them apart and makes them suck far less.
Includes:
- done => then
- fail => catch
- repository.js
- examples are less useless
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate AJAX docs

- src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Fixes #478 
This wraps the standard `DocsVersionDropdownNavbarItem` component from Docusaurus and uses the active document context information to determine whether the current document _has_ any version.
If no version is present, then the code shortcircuits and just returns an empty string.
If there is a version, then the version dowpdown component is called.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/480"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Only show version dropdown in versioned docs

- general/development/process/release/index.md
As discovered in MDLSITE-7028, this is something we forgot to do when 4.1 was released.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/486"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Clarify required AMOS changes following release

- general/releases.md
- general/releases/4.1.md
Add the missing (LTS) to the heading, and the missing release date info.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/488"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add 4.1 LTS details

- general/app/accessibility.md
- general/app/customisation/remote-themes.md
- general/app/development/development-guide.md
- general/app/development/link-handling/app-links.md
- general/app/development/link-handling/deep-linking.md
- general/app/development/plugins-development-guide/index.md
- general/app/development/plugins-development-guide/troubleshooting.md
- general/app/development/release-process.md
- general/app/development/setup/docker-images.md
- general/app/development/testing/acceptance-testing.md
- general/app/faq.md
- general/app/overview.md
- general/app/upgrading/acceptance-tests-upgrade-guide.md
- general/app/upgrading/plugins-upgrade-guide.md
- general/app/upgrading/remote-themes-upgrade-guide.md
- general/app_releases/v3/v3.9.5.md
- src/components.js
- src/components/CodeDiff/index.js
- src/components/CodeDiff/styles.module.css
This PR contains the updated documentation for the upcoming release of the mobile app.
The only part that is not just relevant to mobile is the introduction of a new component called `CodeDiff`, used to compare before/after code snippets in the upgrade guides.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Moodle App 4.1

- data/migratedPages.yml
- docs/apis.md
- docs/apis/_files/db-services-php.mdx
- docs/apis/_files/db-services-php.tsx
- docs/apis/subsystems/external/advanced/_category_.json
- docs/apis/subsystems/external/advanced/custom-services.md
- docs/apis/subsystems/external/description.md
- docs/apis/subsystems/external/files.md
- docs/apis/subsystems/external/functions.md
- docs/apis/subsystems/external/index.md
- docs/apis/subsystems/external/security.md
- docs/apis/subsystems/external/writing-a-service.md
- docusaurus.config.js
- general/app/overview.md
- general/development/policies.md
- general/development/policies/deprecation.md
- general/releases/2.2.md
- package.json
- versioned_docs/version-4.1/apis/subsystems/external/advanced/_category_.json
- versioned_docs/version-4.1/apis/subsystems/external/advanced/custom-services.md
- versioned_docs/version-4.1/apis/subsystems/external/description.md
- versioned_docs/version-4.1/apis/subsystems/external/files.md
- versioned_docs/version-4.1/apis/subsystems/external/functions.md
- versioned_docs/version-4.1/apis/subsystems/external/index.md
- versioned_docs/version-4.1/apis/subsystems/external/security.md
- versioned_docs/version-4.1/apis/subsystems/external/writing-a-service.md
- yarn.lock
This is a first attempt at migrating _some_ of the web service documentation, and improving it.
It's not perfect, but we have to start somewhere. Some of the old documentation was project documentation talking more about what we were thinking of implementing, and very difficult to follow. There was a lot of duplication.
There is still a lot of duplication but it is significantly better than it was.
Other docs will be moved over in different chunks. I can only do so many of these are a time.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Migrate ws docs

- docs/apis.md
- versioned_docs/version-4.1/apis.md
The customfield will also be added to the lib/apis.json file in https://tracker.moodle.org/browse/MDL-76780 (it was missed when this file was created in https://tracker.moodle.org/browse/MDL-71096).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add customfield API name

- general/development/policies/accessibility.md
- yarn.lock
- Make the wording more generic and not just pertaining to a single occasion of the accessibility audit.
- Remove the accreditation badges (especially since they are currently expired) and replace them with links to the accreditation pages.
- List down the dates when WCAG 2.1 Level AA accreditation was issued on the given Moodle versions on a table.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Accessibility docs page tweaks

- docs/apis/subsystems/external/functions.md
- docs/apis/subsystems/external/security.md
- docs/apis/subsystems/external/testing.md
- docs/apis/subsystems/external/writing-a-service.md
- docs/devupdate.md
- general/development/policies/component-communication/index.md
- sidebars/docs.js
- Document the move of `external_api` and friends to the `core_external` subsystem
- Note that pluginland plugins do not need to perform the migration at this time if they do not wish to
- Add a new devupdate page summarising breaking changes in Moodle 4.2
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/506"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update WS docs for MDL-76583

- src/remark/trackerLinks.js
- src/remark/trackerLinks.test.js
The AST processor needed to be told the index of the next node to search in the parent.
Previously we were skipping and stopping processing at that point (`return null == 'skip'`).
When we make a modification to the AST, we must also then return the next index to search - that is the index after the changes.
In this case the next index is previous index + 2. We insert two new items onto the tree:
- the link
- the remainder of the line
We need to process the remainder of the line.
This changeset adds three new unit tests, two of which were previously failing due to this issue.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Address an issue with multiple MDL-s on the same line not being converted to tracker links

- docs/apis/subsystems/external/writing-a-service.md
While trying to refactor a webservice which still depended on the old externallib approach I had some issues, because the docs have some errors - at least I think they are, because I could not get my webservice to work until I figured out what might be the issue by trial and error, so please review carefully.
While creating this PR I also realized that one error already had been fixed 20 days ago in the git repository. Unfortunately the moodledev.io website still shows the error.
https://github.com/moodle/devdocs/blob/38785ebc001af53def9bb6a52b17e8cf7954e90b/docs/apis/subsystems/external/writing-a-service.md?plain=1#L358
vs.
It would be nice, if this could be fixed soon, so noone else is losing some time stumbling over it.
Thank you very much for this really awesome documentation! Really …
> Fix minor, but clutch errors in writing-a-service.md

- general/development/process/release/index.md
As discussed in the iTeam 4.1 retro, we need to prepare Moodle for future PHP versions. This adds a task for 2 weeks after a major release that ensures that such a preparation is made.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Prepare for future PHP versions

- docs/devupdate.md
Inspired by Andrew (https://moodle.org/mod/forum/discuss.php?d=443118) I decided it was a good idea to add a placeholder to the devupdate page, even though the work is not yet finished, so I cannot describe the full scope yet.
If you think adding this placeholder is not a good idea, then please just don't merge this, and I will submit an ameded pull request when it is clear what all the changes in 4.2 are.
I also did this because it game me a chance to record the technique that Luca worked out.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/523"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a placeholder in devupdate about the 4.2 quiz changes

- general/development/policies/php.md
Just add that bit of information now that it has been agreed:
https://tracker.moodle.org/browse/MDL-74905
(Moodle 4.2 requirements issue)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/530"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> PHP 8.0 is now required for Moodle 4.2

- general/development/policies/codingstyle/index.md
Adding whitespace guidelines, especially covering the agreed policy about whitespace before and after the assignment operator `=` in MDLSITE-6594.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDLSITE-6594 Add whitespace guidelines

- general/development/policies/php.md
- general/releases/4.1.md
- Do it in PHP policy page: By MDL-73016, since 4.1.2
- Update 4.1 release notes.
- Also updated a few old examples to actual ones.
(requires [MDL-73016](https://tracker.moodle.org/browse/MDL-73016) to be closed and rolled)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/566"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Declare php81 supported

- general/development/process/integration/index.md
Now they are officially -7w and -6w respectively.
See https://moodledev.io/general/development/process/release
Also, changed slightly the under continuous work organisation to emphasise that the 2 rolls apply to the whole continuous.
Hopefully, that way I'll stop asking every 6 months. :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix the continuous and freeze weeks

- config/algolia.js
WIP/WIP/WIP!
It seems to return way more accurate results than the current one that is really suboptimal.
Sure that more improvements can be done later (robots.txt, better tags handling...). But with this, at very least, the results in general are better.
OT, I've been unable to find from where the Public API key being currently used comes. It doesn't match any search api key in our account.
WIP/WIP/WIP
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/583"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> WIP/WIP/WIP: Try with new re-generated crawl/index

- docs/devupdate.md
Just adding a reminder to include the externallib for making the mentioned aliases work, because I stumbled over it.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/587"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add hint for requiring externallib to devupdate new external subsystem section

- docs/devupdate.md
A reference to the devupdate page for Moodle 4.2 should be added to mention Font Awesome has been upgraded from 4.7 to 6.3.0 in [MDL-76989](https://tracker.moodle.org/browse/MDL-76989).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/569"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add Font Awesome 6 to devupdate (blocked by MDL-76989)

- general/development/process/release/index.md
This task is to be done the week after freeze. Since recently we moved the Freeze week to be -6w (from -5w). So this task needs to be done -5w (from -4w).
The task is documented in the "Standard messages" internal doc ("Raising priority of some minor issues to major" section) and it has been already amended there.
Once/if this is merged, I'll proceed to execute the task and get the priority raised in target issues (no matter we should have executed it 2w ago).
Ciao :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Move the "raise priority to major" task to -5w

- general/community/contribute.md
Change the Moodle academy developer pathway link
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Academy developer pathway link

- general/development/tools/behat/browsers/index.md
- general/development/tools/behat/running.md
- general/development/tools/behat/writing.md
Found them when looking for some info. Surely cause by some bulk search and replace (I imagine).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Lower case the @javascript tags

- general/community/roadmap.md
Removing &selectedIssue=IDEA-86 from https://tracker.moodle.org/secure/RapidBoard.jspa?rapidView=260&projectKey=IDEA
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Removing Kanban board link additional parameter

- general/community/meetings/202305.md
- general/community/meetings/index.md
changes to index page info for next meeting and change to the agenda
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/613"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> changes to index page info for next meeting and change to the agenda

- general/development/policies/accessibility.md
- Updated the table to reflect that 4.0 has finally been given the WCAG 2.1 Level AA accreditation since 3 May 2023.
- Updated the section for 4.2 and 4.1 accreditation with the epic issue. Note that the next audit will be done for Moodle 4.2 which will also cover key new features and improvements from 4.1. That's why they are being grouped together.
- Remove the version from the VPAT URL so it will point to the latest VPAT for the latest accredited Moodle version.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update for 4.0 LMS accessibility accreditation

- general/community/meetings/202305.md
I changed the names of the speakers as there is a last minute change.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> updated names on agenda

- docs/apis/plugintypes/tiny/index.md
A minor change to fix anchors in links to TinyMCE documentation.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/645"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix links to TinyMCE documentation

- docs/apis/plugintypes/mod/index.mdx
Activity language packs are named lang/XX/[modname].php (not mod_[modname].php).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Activity language pack filename

- docs/apis/core/reportbuilder/index.md
These files were moved by MDL-75034 (b3828ce).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/647"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix links for task_logs.php, config_changes.php

- general/development/tracker/labels.md
Document the new **developer_notes** label
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/651"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add developer_notes tracker label

- general/development/tools/phpunit.md
Use an example that actually works in recent Moodle versions.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/653"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix the test file path

- general/development/policies/security/index.md
Since `add_to_log()` was [deprecated](https://github.com/moodle/moodle/blob/MOODLE_402_STABLE/lib/deprecatedlib.php#L38), I changed the sentence to refer to the Events API.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] security: update security measure of logging

- data/migratedPages.yml
Jake points out that the 4.0 developer update docs on the legacy docs points to the 4.2 devupdate notes.
This change fixes that now that we've branched the docs.
Note: We did not start to branch the docs until 4.1 so the 4.0 devupdate notes are listed under 4.1 sadly. 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update devupdate redirect

- docs/apis/subsystems/output.md
Document the new output methods created in MDL-78175.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/659"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78175: Document output renderers methods

- docs/devupdate.md
This commit includes information in the Developer update page for the new activitybadge feature added in https://tracker.moodle.org/browse/MDL-78207
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78207 - [docs] Include activitybadge new feature to Developer update

- docs/apis/plugintypes/format/index.md
As Andrew raised in https://github.com/moodle/devdocs/pull/661 , I've also added this information to the CourseFormat API page :-)
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add ActivityBadge to courseformat API

- versioned_docs/version-4.1/devupdate.md
There don't appear to be any definitions of the MOD_PURPOSE_* constants so it would be useful to have some examples of the kinds of plugins that use these.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Give examples of purpose constants.

- docs/apis/subsystems/external/description.md
- docs/apis/subsystems/external/writing-a-service.md
- general/development/policies/naming.md
Just tidying up the links to the web service naming convention.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a link to the web service naming convention.

- general/development/policies.md
Removed unnecessary question related to Oracle Database support. Question was something like "Is this statement about Oracle true?". It seems to be mistake by someone so removed.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/679"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] policies: Update policies.md

- docs/apis/subsystems/enrol.md
The mod/assignment:submit was replaced by mod/assign:submit.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/695"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Update assignment submit capability name

- docs/apis/core/activitycompletion/index.md
- docs/devupdate.md
This patch adds information about the changes done in [MDL-78528](https://tracker.moodle.org/browse/MDL-78528).
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/699"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78528 - [docs] Append a suffix to the completion rules

- docs/apis/subsystems/output.md
Document the new output methods created in MDL-78282
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/693"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78282 - [docs] Document sr_text output method

- data/component-spelling.txt
- docs/devupdate.md
This explains the most important changes done in https://tracker.moodle.org/browse/MDL-78884
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update MIME icons with SVG

- docs/devupdate.md
Not much to say, the change is 100% transparent for developers BUT for those using custom/hand-made behat.yml files.
Part of [MDL-78934](https://tracker.moodle.org/browse/MDL-78934)
Also, added a brief comment about the removal of --skip-passed ([MDL-78570](https://tracker.moodle.org/browse/MDL-78570))
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/727"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a note about the goutte=>browserkit move (MDL-78934)

- general/community/plugincontribution/checklist.md
adds some common approval blockers to the checklist - in particular the security guidelines and significant namespace collisions are typical blockers.
@mudrd8mz good to have a +1 from you (or a -1) :-)
first dev docs PR so let me know if I've got something wrong...
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/709"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] - plugin checklist approval blockers

- docs/guides/templates/index.md
Add a line to clarify that the `globals` object is only added to template context when one uses the JS Mustache engine -- it is not available for templates using the PHP mustache engine.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] templates: Clarify availability of globals object

- docs/apis/plugintypes/assign/feedback.md
- docs/apis/plugintypes/assign/submission.md
- docs/devupdate.md
- general/development/tools/xmldb.md
- general/releases/4.3.md
Update all the references to the old 28 and 30 char long limits to the new 53 and 63 ones for Moodle 4.3 and up.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Expanded DB identifier sizes (tables and columns - MDL-76459)

- general/contentstyleguide/03-productwriting/confirm-msg.md
- general/contentstyleguide/03-productwriting/index.md
- general/contentstyleguide/03-productwriting/success-msg.md
Adding a new section to the Content style guide.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/730"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Product writing guidelines

- data/migratedPages.yml
While working on [MDL-77708](https://tracker.moodle.org/browse/MDL-77708) I identified a couple of migrated pages that were missed in the data/migratedPages.yml.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [repo] Add missing migrated pages

- general/development/policies/php.md
- general/releases/4.2.md
- general/releases/4.3.md
- Do it in the PHP policy page: By MDL-76405, since 4.2.3
- Update 4.2 release notes.
- Update 4.3 release notes.
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Declare PHP 8.2 supported

- docs/apis/plugintypes/repository/_examples/lib.php
- versioned_docs/version-4.1/apis/plugintypes/repository/_examples/lib.php
- versioned_docs/version-4.1/apis/plugintypes/repository/index.md
- versioned_docs/version-4.2/apis/plugintypes/repository/_examples/lib.php
- versioned_docs/version-4.2/apis/plugintypes/repository/index.md
I'm just working on a new plugin and found this tiny typo in the docs
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] repository plugins: typo fix

- general/development/policies/accessibility.md
Dev docs for when MDL-78806 gets integrated
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/729"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> MDL-78806 better page title documentation

- general/development/tools/phpcs.md
- remove mentinos of phpcs installation via moodle-local_codechecker
-  mention new moodle-extra standard
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/742"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Updates for phpcs documentation

- docs/apis/core/customfields/index.md
- docs/apis/plugintypes/customfield/index.md
- docs/apis/plugintypes/index.md
We use custom fields in Workplace for programs, certifications, appointments and certificates. It was strange to see that this plugin type is called "COURSE custom field" in the docs
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/740"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] corrected custom fields types

- docs/devupdate.md
Add a reference in devupdate page for Moodle 4.3 to explain the changes done about SVG files in https://tracker.moodle.org/browse/MDL-67271
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/732"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add missing SVG files to devupdate

- general/development/tools/behat/writing.md
Currently, the example repeats the `@javascript` tag in the scenario, even though it is already present in the feature's header. This is not necessary and would actually give a `duplicate-behat-tag` warning.
I suggest changing the example and adding a note that explains how tags defined at feature level will automatically apply to all scenarios of that feature.
> Writing acceptance tests: do not repeat feature-level tags for scenario

- src/components/ProjectSummary/index.tsx
- src/components/ProjectSummary/styles.module.css
I suggest to wrap ProjectSummary in div container with some minor style change, so it looks a little more "technical" and has space from the left side.
Before:
After:
(feel free to reject, spotted that parapgraph text touches the table while reading docs and thought would be good to improve slightly)
> Make ProjectSummary more visually appealing.

- general/development/process/peer-review/index.md
Here are three proposed changes to the Peer review checklist, as three separate commits.
It might have been a mistake to send them as a single pull request, because while I think the first two should be uncontentious, the third one might need more discussion. If you want me to separate them out, just ask (or you can do it yourself).
The three changes are:
1. Move the overall checklist item to the end.
2. Rename it to 'Overall completeness and correctness' to more clearly name what it is for and because the Moodle content guideliness specifically [tell us to avoid the phrase 'sanity check'](https://moodledev.io/general/contentguidelines/styleguide/voice/contentprinciples#words-and-phrases-to-avoid).
3. Change the Accessibility check so that it is no longer 'optional'. That sent such a …
> Peer review checklist improvements

- general/development/process/peer-review/index.md
Sorry, I missed this in the previous change.
> Peer review checklist: remove another 'optional'

- general/community/plugincontribution/pluginsdirectory/updates.md
The Plugins directory updates page was recently created, but the Update link was not properly positioned in the sidebar and the title was not set. This patch sets the title and locates the Update link in the first position within the group.
> [docs] Fix plugins update page sidebar title and position

- data/migratedPages.yml
- general/development/policies/codingstyle/index.md
- general/development/policies/deprecation/index.md
- general/development/policies/deprecation/scss-deprecation.md
- general/development/process.md
- general/development/process/peer-review/index.md
- general/development/process/release/index.md
- Convert the current "Deprecation" page into a subsection, moving `deprecation.md` to `/deprecation/index.md`
- Add a new "SCSS deprecation" page under this new "Deprecation" subsection
> [docs] Add SCSS deprecation page

- general/app/development/_category_.yml
- general/app/development/index.md
- general/app/development/link-handling/_category_.yml
- general/app/development/link-handling/index.md
- general/app/development/plugins-development-guide/examples/_category_.yml
- general/app/development/plugins-development-guide/examples/index.md
- general/app/development/scripts/_category_.yml
- general/app/development/scripts/index.md
- general/app/development/testing/_category_.yml
- general/app/development/testing/index.md
- general/app/upgrading/_category_.yml
- general/app/upgrading/index.md
- general/app_releases/v2/_category_.yml
- general/app_releases/v2/index.md
- general/app_releases/v3/_category_.yml
- general/app_releases/v3/index.md
- general/app_releases/v4/_category_.yml
- general/app_releases/v4/index.md
Before this commit, some urls of parent pages did not match the child urls. This was not future-proof because urls could change if a category page is ever converted to a text page.
> Fix category page urls in app docs

- docs/apis/subsystems/external/advanced/custom-services.md
> fix: typo at webservices advanced docs

- general/releases.md
Updated `will end` to `ended` for 4.1's general support and 4.0, 3.11, and 3.9's general support info.
> Minor support info wording updates for 4.1, 4.0, 3.11, and 3.9

- src/css/custom.css
The validexample and invalidexample components fail the WCAG AA level because of the lack of colour contrast of the text. Changing the text to black fixes the issues.
> [repo] Meet WCAG AA level for Valid/Invalid example components

- docs/devupdate.md
This documentation was previously backwards and had the user-focused part of the documentation first.
The key part here is the _developer_ documentation regarding the method. The CSV format information is present to make testing easier and will also be present in the user docs.
> [docs] Tidy up the devupdate to prioritise dev docs

- general/development/policies/backporting.md
- general/development/policies/deprecation/index.md
I noticed an incorrectly terminated admonition, and then in fixing it tried to improve the language.
I also notethat there are only two files using "See also..." instead of "See also".
> [docs] Improve wording for backport policy

- general/development/policies/php.md
It was decided @ https://tracker.moodle.org/browse/MDL-78496 that PHP 8.1 will be required for Moodle 4.4 and up.
Hence, documenting it here. This corresponds to TODO-16, point #1 in the issue above.
> PHP 8.1 is required for Moodle 4.4 and up

- general/projects/api/string-deprecation.md
Fixing broken layout (https://moodledev.io/general/projects/api/string-deprecation#what-to-do-if-you-get-a-debugging-message):
> [docs] api: Fix string-deprecation admonition closing tag.

- docs/apis/subsystems/external/testing.md
- versioned_docs/version-4.1/apis/subsystems/external/testing.md
- versioned_docs/version-4.2/apis/subsystems/external/testing.md
- versioned_docs/version-4.3/apis/subsystems/external/testing.md
Test class files do not seem to have access to global variables, so there is the need of declaring `global $CFG;` for this example to work.
Another possibility would be to use a relative path for the require_once statement. Not sure what is the better option in this case.
> Add global definition of $CFG

- docs/apis/subsystems/group/index.md
in the "How to get just the groups that the current user can see" example
> Group API: Fix typos in code examples

- general/development/policies/deprecation/index.md
Add a note to explain that asserDebugginCalled() should be added to unit tests that cover a deprecated function, to prevent them failing until the function is removed.
> Add note to function deprecation about unit tests

- docs/apis/plugintypes/mod/activitymodule.md
- versioned_docs/version-4.1/apis/plugintypes/mod/activitymodule.md
- versioned_docs/version-4.2/apis/plugintypes/mod/activitymodule.md
- versioned_docs/version-4.3/apis/plugintypes/mod/activitymodule.md
While reviewing https://tracker.moodle.org/browse/MDL-80434 I realised there was a mistake in the docs, because they were referring to **_get_content_items** instead of **_get_course_content_items** (which was the real method that replaced get_shortcuts()).
> [docs] Fix wrong function name for activitychooser

- docs/apis/core/hooks/index.md
The naming convention for hooks has been decided in MDL-79077. The statement that hook classes should follow the standard pattern of general to more specific conflicts with the policy that is on the `Hook policies` section. It is better to remove it to avoid confusion.
> Remove hook naming convention that conflicts with the policy

- general/development/policies/deprecation/index.md
Thanks to Paul Holden's review I realized that dev docs don't mention deprecated behat steps should be moved to component directory instead of lib/tests/behat/behat_deprecated.php.
I discussed with Júlia the added information. I hope that's OK.
Thanks both for your help :-)
Amaia
> MDL-75794: Improve behat steps deprecation process documentation

- docs/devupdate.md
This is for documenting changes in https://tracker.moodle.org/browse/MDL-80395. In BS5 some previously deprecated mixins are dropped. They can be refactored without waiting for the BS upgrade.
> [docs] Dev update Bootstrap mixins refactor - MDL-80395

- docs/apis/subsystems/external/functions.md
- versioned_docs/version-4.1/apis/subsystems/external/functions.md
- versioned_docs/version-4.2/apis/subsystems/external/functions.md
- versioned_docs/version-4.3/apis/subsystems/external/functions.md
Adding the missing PHP semi-colon on 4 examples of external API use.
> missing semi-colon in external apis

- docs/devupdate.md
- docs/guides/bs5migration/index.md
- Move Bootstrap 5 migration process information from devupdate to a new page
- Improve Migration process information
> [docs] Move Bootstrap 5 migration to a new page

- docs/apis/core/hooks/index.md
- docs/devupdate.md
> [docs] Add docs for array notated hook callbacks

- general/development/tools/exceptiontracing.md
> [docs] Whoops debugging as error docs - MDL-80206

- docs/apis/plugintypes/qbank/index.md
- docs/apis/plugintypes/qtype/index.md
- docs/apis/plugintypes/qtype/newquestiondefaults.md
- docs/apis/subsystems/question/index.md
Fully documenting core_question and all the related plugin types is going to be a mammoth task 🦣🦣🦣.
But a journey of a thousand miles starts with a single step, or some other trite cliche, so here is one.
All this because I wanted to explain newquestiondefaults.md in MDL-79863 - and it was obviously better to do that in the dev docs than a tracker comment, and I needed to build a framework to put that in.
> Start documenting core_question and qbank_

- .github/workflows/lighthouse-report.yml
Now that we have more supported branches in docs, it takes longer to build them.
> [repo] Bump lighthouse timeout

- .github/workflows/lighthouse-report.yml
In https://github.com/moodle/devdocs/pull/920/ the version was changed from 1.0.6 to 1 (which doesn't exist). I'm putting back the original value because Netlify preview is not working (for instance, https://github.com/moodle/devdocs/pull/940)
> [repo] Fix version for Wait for the Netlify Preview job

- docs/apis/subsystems/check/index.md
- versioned_docs/version-4.1/apis/subsystems/check/index.md
- versioned_docs/version-4.2/apis/subsystems/check/index.md
- versioned_docs/version-4.3/apis/subsystems/check/index.md
See: https://tracker.moodle.org/browse/MDL-72335
> [doc] tool_health was removed

- general/development/policies/php.md
- Do it in the PHP policy page: By MDL-76426, since 4.4
- Update 4.4 release notes (not needed in this case, it's already showing the correct PHP 8.3 information).
Note: Creating this as draft, we need:
- #952 implemented (4.4 release page available).
- This PR modified to ensure that the 4.4 release page has correct information.
- [MDL-76426](https://tracker.moodle.org/browse/MDL-76426) completed.
See #734 for the PHP 8.2 sister PR of this.
> Declare PHP 8.3 supported

- general/development/tools/mdk.md
This removes references to old versions, which should not be wanting to develop for, because they are unsupported
> Only reference current versions

- .markdownlint/fix-renamed-links.js
- config/navbar.js
- docs/devupdate.md
- docs/guides/bs5migration/index.md
- docusaurus.config.js
- general/development/tracker/labels.md
- nextVersion.js
- src/components/HomepageFeatures/index.js
- src/remark/unversionedDocsLinks.js
- static/_redirects
This commit changes the unversioned docs at /docs/ to instead be at /docs/[nextVersionNumber].
It includes a redirect for /docs/* (where an existing page is not found) and it adds helpers to specify the version number in URLs and other locations.
Fixes #955
> [repo] Adjust /docs to include next version

- docs/guides/javascript/reactive/index.md
This repository turned out to be incredibly helpful for me, I really think it should be referenced on top of the developer resources page for the new reactive library.
> Add example/tutorial repo mod_nosferatu for reactive library page

- docs/apis/subsystems/output/inplace.md
- versioned_docs/version-4.3/apis/subsystems/output/inplace.md
> Add working examples and some clarifications to inplace_edit

- docs/apis/subsystems/communication/index.md
Some weird spacing here mainly.
> [docs] Tidy up examples to meet coding style

- docs/devupdate.md
> Meta enrolment in csv course upload

- general/community/credits/testing.md
As suggested in the iteam chat, it would be better to display the list of testing credits showing the recent Moodle release first.
> reorder testing credits list showing recent release first

- docs/guides/profiling/index.md
The tideways_xhprof extentension is no longer maintained, from the GitHub README:
> This XHProf PHP extension fork has outlived its purpose and is 
> archived in favor of the revitalized PECL XHProf extension
> that is also using the modern PHP profiling abilities and 
> performant timer APIs.
> Remove tideways references from Profiling documentation

- data/migratedPages.yml
- general/community/contribute.md
Migrated pages :
* https://docs.moodle.org/dev/New_feature_ideas
Closes #173 
<a href="https://gitpod.io/#https://github.com/moodle/devdocs/pull/200"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Migrate new features and ideas

- general/development/policies/backporting.md
- Add the policy for backporting accessibility fixes to the LTS branch as decided in [MDLSITE-7330](https://tracker.moodle.org/browse/MDLSITE-7330)
- Additional change to remove the reference to the `master` branch and replace it with the reference to the `main` branch.
> Update backport policy for accessibility fixes

- data/migratedPages.yml
- docs/apis/plugintypes/theme/_examples/lang.md
- docs/apis/plugintypes/theme/_examples/lang.php
- docs/apis/plugintypes/theme/fonts.md
- docs/apis/plugintypes/theme/images.md
- docs/apis/plugintypes/theme/index.md
- docs/apis/plugintypes/theme/layout.md
- docs/apis/plugintypes/theme/styles.md
For now, I'll start migrating the content in https://docs.moodle.org/dev/Themes_overview and then I'll improve the content, adding information from other pages in the Theme section, like https://docs.moodle.org/dev/Using_images_in_a_theme#Image_locations_within_Moodle
> [docs] Migrate Themes overview

- docs/guides/javascript/index.md
- versioned_docs/version-4.1/guides/javascript/index.md
- versioned_docs/version-4.2/guides/javascript/index.md
- versioned_docs/version-4.3/guides/javascript/index.md
- versioned_docs/version-4.4/guides/javascript/index.md
The missing quote means the JS is invalid. This fixes it.
> Add ' to create valid JS on selectors

- docs/devupdate.md
This should be integrated when https://tracker.moodle.org/browse/MDL-81872 is merged.
> [docs] Explain changes done in reset course page - Blocked by MDL-81872

- general/development/tools/generator.md
MDL-81885 allows admin_generator to execute the "the_following_config_values_are_set_as_admin behat step". Prior to this patch, the tool could only execute the standard generator steps.
I also moved the execution process to its own section so it can be linked directly to the issues when needed.
> [docs] Improve generator tool using behat - MDL-81885

- data/migratedPages.yml
I realized some of the migrated pages were not correct, I wonder if it would be possible to lint these in some way?
Other than that, there was a page we had migrated, but we removed it recently because it's no longer relevant. Is there a way to mark a page as "deleted" rather than migrated?
> MOBILE-4616: Update migrated app pages

- docs/devupdate.md
In MDL-43938, the badges/newbadge.php page has been deprecated and merged with badges/edit.php.
> [docs] Deprecation of the badges/newbadge.php page - MDL-43938

- general/development/policies/deprecation/index.md
As we've discussed with each deprecation of a public file, like in MDL-43938 with badges/newbadge.php, I've added an explicit reference to it. This will help us remember the agreed-upon process in the future.
> [docs] Add reference to public files deprecation

- versioned_docs/version-4.1/guides/javascript/modal/index.md
- versioned_docs/version-4.2/guides/javascript/modal/index.md
We need to import ModalRegistry not ModalFactory when defining a new Modal Class for creating custom modal types
> Import ModalRegistry instead of ModalFactory

- docs/apis/subsystems/output/index.md
- versioned_docs/version-4.3/apis/subsystems/output/index.md
- versioned_docs/version-4.4/apis/subsystems/output/index.md
Please consider backporting this fix to the versioned docs folder.
> output: Clarify format_string() parameters

- general/development/policies/accessibility.md
WebKey IT used to list its clients' accreditations on its website. However, since it was acquired by AbleDocs and later became GrackleDocs, it no longer seems to update this list.
Because of this, the link to the "WCAG 2.1 Level AA conformance" in our dev docs points to an old accreditation. I think it's better to replace the link with a URL to the actual statement of conformance that is currently on the 4.2 accessibility audit epic (MDL-78185).
> Link to the statement of conformance file

- general/development/policies/security/crosssite-request-forgery.md
`sesskey` is often confused with Moodle Session ID cookie. This change updates Session Key section at Cross-site request forgery page, clarifying its purpose as CSRF token.
Rendered page: https://deploy-preview-1083--moodledevdocs.netlify.app/general/development/policies/security/crosssite-request-forgery#session-key
> [docs] Make clear that sesskey is CSRF token.

- docs/devupdate.md
This issue is to document changes done in [MDL-82497](https://tracker.moodle.org/browse/MDL-82497), [MDL-82211](https://tracker.moodle.org/browse/MDL-82211) and [MDL-82210](https://tracker.moodle.org/browse/MDL-82210).
> [docs] Update devupdate with FA6 info

- docs/guides/profiling/index.md
- versioned_docs/version-4.3/guides/profiling/index.md
- versioned_docs/version-4.4/guides/profiling/index.md
Specify the value for `XDEBUG_PROFILE` param to solve this issue: The trigger value '', as set through 'XDEBUG_PROFILE', did not match the shared secret (xdebug.trigger_value) for mode 'profile'.
> Specify value for XDEBUG_PROFILE in profiling page 

- docs/devupdate.md
- general/development/policies/deprecation/icon-deprecation.md
- general/development/policies/deprecation/index.md
- general/development/policies/deprecation/scss-deprecation.md
In https://tracker.moodle.org/browse/MDL-82212 a new deprecation mechanism has been implemented to remove icons.
> [general] Add Icon deprecation policy [MDL-82212]

- docs/apis/plugintypes/mod/_files/lib_description.md
Since MDL-81767, there is a new FEATURE_QUICKCREATE that needs to be documented.
> [docs] document some activity [modname]_supports features

- docs/devupdate.md
In [MDL-82503](https://tracker.moodle.org/browse/MDL-82503), `badges/index.php` and `badges/view.php` pages and `course_badges` and `badges` system reports have been combined.
As a result, `badges/view.php` and `course_badges` have been deprecated.
> [docs] Deprecated badges/view.php and course_badges system report [MDL-82503]

- general/development/process/peer-review/index.md
This edit is in response to having to keep saying the same thing about changes that have come to me to CLR, after someone claims to have peer reviewed them. I hope this is not too opinionated.
> Improve the 'testing' part of the peer review checklist

- docs/guides/bs5migration/index.md
[devdoc] Devdocs Bootstrap theme-color-level refactor
Blocked by [MDL-81816](https://tracker.moodle.org/browse/MDL-81816)
> Devdocs bootstrap theme color level [MDL-81816]

- general/development/process/release/newuserdocs.md
The previous version did not seem to work.
Ref: https://www.mediawiki.org/wiki/Help:Redirects
> Fix the REDIRECT syntax

- docs/apis/plugintypes/ai/index.md
- docs/apis/plugintypes/ai/placement.md
- docs/apis/plugintypes/ai/provider.md
- docs/apis/subsystems/ai/index.md
AI subsystem and associated placement and provider plugins documentation: [MDL-82627](https://tracker.moodle.org/browse/MDL-82627)
> Docs for AI Subsystem for: MDL-82627

- docs/apis/subsystems/privacy/faq.md
- versioned_docs/version-4.1/apis/subsystems/privacy/faq.md
- versioned_docs/version-4.2/apis/subsystems/privacy/faq.md
- versioned_docs/version-4.3/apis/subsystems/privacy/faq.md
- versioned_docs/version-4.4/apis/subsystems/privacy/faq.md
It appears that this is not clear to everyone who reads the documentation at the moment that a plugin that sends data to a subsystem, for example the logs should not use the null_provider and that the sub-system will do the retrieval and deletion of the personal data.
> How to handle privacy providers that only store data in a sub-system

- docs/apis/plugintypes/filter/index.md
https://moodledev.io/docs/4.5/apis/plugintypes/filter#filterphp
This has changed to classes/text_filter.php in 4.5.
> [docs] Fix filter plugintype main class header

- general/development/tools/phpunit.md
Updating https://moodledev.io/general/development/tools/phpunit#phpunit-versions to reflect latest release.
(per https://tracker.moodle.org/browse/MDL-79809)
> Update phpunit 9.6 Moodle versions range support

- general/development/policies/deprecation/index.md
Update the final deprecation policy to align with the LTS release cycle and version numbering updates as [announced in the forums](https://moodle.org/mod/forum/discuss.php?d=457946).
> Update the final deprecation policy

- docs/intro.md
- general/documentation/forking-versions.md
- src/components/ReleaseStateSummary/index.tsx
I thought I had already sorted out this in #1162, but apparently, I missed it. 
I also added another commit that fixes the wording for future non-LTS versions in the release state summary.
> Fix the intro page for the 5.0 dev docs

- general/development/process/integration/index.md
Clarify and provide more information regarding the issues related to the major release, especially during the last week before the release
> Update the wording for the "Last week before the release"

- package.json
- yarn.lock
This dependency is now available pre-built for MacOS on ARM. The previous version is no longer buildable.
> [repo] Bump libxmljs2 to latest

- docs/apis/subsystems/routing/index.md
- docs/apis/subsystems/routing/parameters.md
- docs/apis/subsystems/routing/responses.md
- docs/apis/subsystems/routing/testing.md
- versioned_docs/version-4.5/apis/subsystems/routing/index.md
- versioned_docs/version-4.5/apis/subsystems/routing/parameters.md
- versioned_docs/version-4.5/apis/subsystems/routing/responses.md
- versioned_docs/version-4.5/apis/subsystems/routing/testing.md
[MDL-81031](https://tracker.moodle.org/browse/MDL-81031)
> [docs] Add docs for routing engine - MDL-81031

- docs/apis/subsystems/output/index.md
- docs/guides/templates/index.md
- versioned_docs/version-4.1/guides/templates/index.md
- versioned_docs/version-4.3/apis/subsystems/output/index.md
- versioned_docs/version-4.3/guides/templates/index.md
- versioned_docs/version-4.4/apis/subsystems/output/index.md
- versioned_docs/version-4.4/guides/templates/index.md
- versioned_docs/version-4.5/apis/subsystems/output/index.md
- versioned_docs/version-4.5/guides/templates/index.md
We probably want to let people know about named templates and the ability to save on writing some boiler plate code when using templates in the Output API
> Document named_templates

- docs/apis/subsystems/output/inplace.md
- versioned_docs/version-4.3/apis/subsystems/output/inplace.md
- versioned_docs/version-4.4/apis/subsystems/output/inplace.md
- versioned_docs/version-4.5/apis/subsystems/output/inplace.md
The current document is outdated since the code have changes.
So it is hard to using the example as references.
> Update Inplace editable docs with new events and template

- docs/apis/commonfiles/version.php/index.md
- versioned_docs/version-4.1/apis/commonfiles/version.php/index.md
- versioned_docs/version-4.3/apis/commonfiles/version.php/index.md
- versioned_docs/version-4.4/apis/commonfiles/version.php/index.md
- versioned_docs/version-4.5/apis/commonfiles/version.php/index.md
$plugin->incompatible = [401];
Wrongly defined in the example
It require an Integer and not an array
> fix #1180 Update index.md $plugin->incompatible

- general/development/policies/php.md
This applies the policy proposal made as Option B.
> [docs] Update PHP Version Support statement (MDLSITE-7677)

- docs/apis/core/hooks/index.md
- versioned_docs/version-4.3/apis/core/hooks/index.md
- versioned_docs/version-4.4/apis/core/hooks/index.md
- versioned_docs/version-4.5/apis/core/hooks/index.md
Interface '\core\hook\hook_discovery_agent' does not exist in the \core\hook, it should be '\core\hook\discovery_agent'.
> Change discovery_agent interface name

- .markdownlint/fix-renamed-links.js
Before this change the way links formed differed based on operating system.
This meant that on Windows the fix-renamed links checker would both change links that it should not, and leave them with Windows style slashes.
This is a fix for Issue #1197
> Fix link checker on Windows

- general/development/policies/deprecation/index.md
The deprecation process has several mentions of adding notes to upgrade.txt. This is no longer the current process, so I have replaced these with links to the upgrade notes documentation.
> Replace references to upgrade.txt in deprecation docs.

- docs/apis/core/reportbuilder/filtering.md
- docs/apis/core/reportbuilder/index.md
- versioned_docs/version-4.3/apis/core/reportbuilder/filtering.md
- versioned_docs/version-4.3/apis/core/reportbuilder/index.md
- versioned_docs/version-4.4/apis/core/reportbuilder/filtering.md
- versioned_docs/version-4.4/apis/core/reportbuilder/index.md
- versioned_docs/version-4.5/apis/core/reportbuilder/filtering.md
- versioned_docs/version-4.5/apis/core/reportbuilder/index.md
I have:
- Added documentation for creating data sources for custom reports
- Setting filter conditions in code
- Added some additional tips for creating entities
- Pointed code examples at the branch of Moodle the docs are for
I have attempted to ensure that the docs include API changes that have happened since Moodle 4.3
This change should hopefully implement most of the improvements I think would be useful in Issue #1192
> Update report builder API docs

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-81825
> [docs] Documentation for MDL-81825

- docs/apis/core/dml/index.md
- versioned_docs/version-4.1/apis/core/dml/index.md
- versioned_docs/version-4.3/apis/core/dml/index.md
- versioned_docs/version-4.4/apis/core/dml/index.md
- versioned_docs/version-4.5/apis/core/dml/index.md
Presumably this function is missing and wasn't deliberately omitted?
Can this change be cherry-picked to the 4.4 and 4.5 docs or should these be changed in separate requests?
> Add get_fieldset()

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-81821
> [docs] Documentation for MDL-81821

- general/development/policies/deprecation/index.md
- general/development/tools/behat/writing.md
It is possible to deprecate behat steps, but currently this is only documented in the comments on the `behat_deprecated_base` class. This adds an explanation and example of how to use this class to deprecate a behat step.
> Add deprecation docs for behat steps

- data/versions.json
- general/releases.md
- general/releases/4.6.md
- sidebars/releaseNotes.js
- src/theme/UnsupportedVersionBanner/index.js
- src/utils/SupportedReleases.ts
- static/schema/versions.json
This adds the ability to define an experimental release, which is omitted from the main releases nav and the release table, and adds a warning on the release notes page. This is then implemented for the 4.6 experimental release, which was made available today.
For the record: It's intentional that the upgrade link for 4.6 points to 4.5.
> Experimental release support and 4.6 docs

- general/development/process/peer-review/index.md
At least, this seems more logical to me:
* Move the checkes that are more overall to the end.
* Group all the UI, and DB/performance together.
Also, add mention of developer_notes label which I always forget.
> Re-order the peer review checklist into a more logical order

- general/development/abc/fixups.md
> Fix typos in fixups.md

- docs/devupdate.md
Adding an update note about the new activity purpose colors SCSS variables.
> MDL-83725 activity icon colors update note

- general/development/abc/fixups.md
I just replaced the typo `git commit --ammend` by `git commit --amend`
Ref: [https://moodledev.io/general/development/abc/fixups](https://moodledev.io/general/development/abc/fixups#:~:text=git%20commit%20-a%20--ammend)
> [docs] Fix a small typo on a git command in fixups.md

- general/development/policies/node.md
This version policy is a migration from tracker issues.
I have also taken the opportunity to tidy this up, and update it in line with the version policy changes introduced in IDEA-168.
> [docs] Update the NodeJS version policy

- docs/devupdate.md
Add an upgrade note about all YUI and 3.11 course format deprecation in Moodle 5.0
> MDL-83527 course format update note

- docs/apis/plugintypes/ai/provider.md
> Update AI Provider plugin documentation for provider instances.

- docs/apis/plugintypes/qbank/filters.md
- docs/apis/plugintypes/qbank/index.md
- versioned_docs/version-4.3/apis/plugintypes/qbank/filters.md
- versioned_docs/version-4.3/apis/plugintypes/qbank/index.md
- versioned_docs/version-4.4/apis/plugintypes/qbank/filters.md
- versioned_docs/version-4.4/apis/plugintypes/qbank/index.md
- versioned_docs/version-4.5/apis/plugintypes/qbank/filters.md
- versioned_docs/version-4.5/apis/plugintypes/qbank/index.md
This functionality was added in MDL-72321. MDL-78220 will add several new filters, so this guide may expand as the children of that tracker are developed.
> Add question bank filter API guide

- .husky/pre-commit
- package.json
Yarn 2 does not run the `prepare` script. We need to switch to `postinstall` or `install`. Husky recommends using the postinstall.
> [repo] Update Husky installation for Yarn2

- general/development/process/peer-review/index.md
The reply templates for pasting into the tracker still had the old links to docs.moodle.org/dev.
> [docs] replace old docs links with their new counterparts

- general/development/policies/deprecation/plugin-removal.md
This PR starts to formulate a process for removing plugins from core.
> [docs] Add notes about plugin removal from core

- general/development/process/peer-review/index.md
In #1246 I was made aware by @andrewnicols that I placed the wrong links. Let's fix this.
> [docs] fix links to devdocs

- docs/apis/plugintypes/mod/courseoverview.md
- docs/devupdate.md
Explanation on how to integrate a plugin with the course overview page.
> MDL-83872 Course overview integration

- docs/apis/plugintypes/mod/courseoverview.md
This is the documentation of the new redirect method implemented in MDL-83892.
> MDL-83892 Activity overview redirection

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-80519
> [docs] Documentation for MDL-80519

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-84450
> [docs] Documentation for MDL-84450

- docs/devupdate.md
Add Bootstrap 5 update to the developer update for 5.0 linking to the Bootstrap 5 migration page
> [docs] Add Bootstrap 5 upgrade to Developer update

- general/development/tools/phpunit/index.md
tool_dataprivacy_metadata_registry_testcase was removed so it should be replaced
> [general] Fix unexisting PHPUnit filter test

- docs/apis/plugintypes/mod/courseoverview.md
- docs/apis/subsystems/output/index.md
Documentation related to [MDL-84602](https://tracker.moodle.org/browse/MDL-84602).
> MDL-84602 add overview item documentation.

- general/development/policies/deprecation/index.md
The documentation for deprecation needed clarifying for how to handle the final deprecation process.
As Moodle code is more OOP we can't follow the existing final deprecation steps.
> Final deprecation policy update to keep method signature

- docs/apis/plugintypes/ai/provider.md
- docs/apis/subsystems/ai/index.md
> Update AI Provider plugin documentation for Pre-defined Models

- general/development/policies/php.md
- Do it in the PHP policy page: By MDL-80117, since 5.0
- Update 5.0 release notes (not needed in this case, it's already showing the correct PHP 8.4 information).
> Declare PHP 8.4 supported

- general/app/development/plugins-development-guide/api-reference.md
As we struggled with this and an example like this would have helped a lot, I would like to add this.
> Example how to open a Moodle course within the Moodle App

- docs/apis/plugintypes/mod/_files/lib_description.md
- docs/devupdate.md
- versioned_docs/version-4.5/apis/plugintypes/mod/_files/lib_description.md
Documentation about the replacement for core_courseformat_create_module created in MDL-83469.
> MDL-83469 adding core_courseformat_new_module references

- docs/apis/subsystems/output/index.md
https://tracker.moodle.org/browse/MDL-81714
> MDL-81714 Update stored progress API example

- docs/guides/bs5migration/index.md
This PR is related to https://tracker.moodle.org/browse/MDL-85127
> [docs] Documentation for MDL-85127

- general/community/credits/testing.md
- general/development/process/testing/qa.md
As part of the QA test process, this PR includes the name of the QA testers and a link to the 5.0 QA cycle
> Add link and list of 5.0 QA testers

- CODEOWNERS
The @moodle/iteam team is a secret team and can't be used in code owners.
I have:
* created a new documentation-owners team to replace iteam
* added the existing mobile-developers team to the app locations
* added a new content-authors team with Julia for the content guidelines section
* added a new community team for the community section
> [repo] Update code owners

- docs/apis/subsystems/external/description.md
- docs/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.1/apis/subsystems/external/description.md
- versioned_docs/version-4.1/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.3/apis/subsystems/external/description.md
- versioned_docs/version-4.3/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.4/apis/subsystems/external/description.md
- versioned_docs/version-4.4/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.5/apis/subsystems/external/description.md
- versioned_docs/version-4.5/apis/subsystems/external/writing-a-service.md
Some declarations had closing parenthesis when closing brackets needed.
[Check Actual External Function Declarations Docs](https://moodledev.io/docs/5.0/apis/subsystems/external/description)
> Fix typos on external services declaration examples

- docs/apis/subsystems/files/index.md
- versioned_docs/version-4.1/apis/subsystems/files/index.md
- versioned_docs/version-4.3/apis/subsystems/files/index.md
- versioned_docs/version-4.4/apis/subsystems/files/index.md
- versioned_docs/version-4.5/apis/subsystems/files/index.md
parameters list with an dot instead of comma
> Fix typo in code example

- general/development/policies/php.md
According to the composer.json file in the MOODLE_500_STABLE branch PHP 8.2 is the minimum version for Moodle 5.0+
I am not sure, if this is a misunderstanding by me, but I found it to be confusing.
> Update Minimum PHP verion for Moodle 5.0+

- data/versions.json
- general/releases/5.2.md
- general/releases/5.3.md
- src/components/SupportedReleases/index.tsx
- src/utils/SupportedReleases.ts
- static/schema/versions.json
This changset also adds the ability to hide dates so that we can have them in the calendar but not visible just yet.
> 5.x Release dates

- src/theme/Navbar/index.js
- src/theme/Navbar/index.module.css
Hi,
According to the Moodle sites issues:
- https://tracker.moodle.org/browse/MDLSITE-7941
- https://tracker.moodle.org/browse/MDLSITE-7956
I applied the necessary changes to keep the top bar consistent across all community environments and highlight the current page in the menu. Additionally, I am improving accessibility in the waffle menu.
> MDLSITE-7941 MDLSITE-7956: Improve waffle menu title and top bar site indication

- docs/apis/subsystems/external/functions.md
- docs/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.4/apis/subsystems/external/functions.md
- versioned_docs/version-4.4/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-4.5/apis/subsystems/external/functions.md
- versioned_docs/version-4.5/apis/subsystems/external/writing-a-service.md
- versioned_docs/version-5.0/apis/subsystems/external/functions.md
- versioned_docs/version-5.0/apis/subsystems/external/writing-a-service.md
These functions have been renamed in Moodle 4.2.
See
- https://web.archive.org/web/20241102043138/https://moodledev.io/docs/4.2/devupdate#external-api
- https://672834180938720008adb671--moodledevdocs.netlify.app/docs/4.2/devupdate#renamed-external-api-classes
- https://moodle.org/mod/forum/discuss.php?d=457297
> [docs] Fix imports in External Services examples

- docs/apis/subsystems/form/index.md
- versioned_docs/version-4.1/apis/subsystems/form/index.md
- versioned_docs/version-4.4/apis/subsystems/form/index.md
- versioned_docs/version-4.5/apis/subsystems/form/index.md
- versioned_docs/version-5.0/apis/subsystems/form/index.md
- provide full example including `<?php` tag when providing an example file. If an example references a filename the code block should contain a complete example of this file.
- specify namespace according to the automatic class loading rules
- add backslash to `moodleform` for namespaced reference (`use moodleform` would also be fine)
---
Not sure if `use moodleform` is preferred to `extends \moodleform`. The [style guide](https://moodledev.io/general/development/policies/codingstyle#further-notes) seems to say that both variants are fine?
> [docs] Provide full example for Forms API

- general/documentation/accessibility.md
Accessibility statement based on moodle.org Accessibility statement (MDLSITE-8064)
> Accessibility statement based on moodle.org statement

- general/documentation/accessibility.md
Title changed to 'Accessibility statement' and note added with pointer to existing Accessibility page as suggested in MDLSITE-8064.
> Title change and note added with pointer to existing Accessibility page

- general/development/policies/codingstyle/index.md
This change updates the coding style to remove legacy line wrapping rules, and other parts which are explicitly defined by PSR-12.
> [docs] Updating coding style per MDLSITE-7597

- docs/apis/plugintypes/mod/courseoverview.md
- docs/apis/subsystems/output/index.md
> [MDL-85509] activity overview webservices

- data/migratedPages.yml
- docs/guides/testing/index.md
- general/development/policies/codingstyle/index.md
- general/development/tools/behat/writing.md
- general/development/tools/phpunit/index.md
- general/releases/3.11.md
- general/releases/3.4.md
This is the start of migrating the phpunit docs.
We should land this and then add more detail re:
- use of attributes
- best practice
- `assertInstanceOf('some_stupid_string_class')` is bad
> MIgrate phpunit docs

- general/releases/4.1.md
- general/releases/4.4.md
- general/releases/4.5.md
- general/releases/5.0.md
- general/releases/5.1.md
- general/releases/5.2.md
- general/releases/5.3.md
The language previously used to describe when a system requirement version was bumped was really confusing: "increase since" mean "has increased since", which is confusing when you are looking at notes for a version beyond where it was bumped, because it sounds like the version listed is when it changed, when i twas actually changed in the release after that. For example  the 4.5 notes had "increased since Moodle 4.1" which actually meant something increased in 4.2...
I have updated all of the currently supported versions and the documented future versions (4.1, 4.4, 4.5, 5.0, 5.1, 5.2, 5.3) so that they say "increased in this Moodle version" in the initial version where a bump has occurred, and in subsequent versions it now says "last increased in Moodle X.Y" and lists the specific …
> [docs] Make system requirement bumps clearer in supported versions

- docs/devupdate.md
[docs] custom activity chooser footer changes
> MDL-85597 Documenting changes to the activity chooser custom footer integration.

- docs/apis/core/comment/index.md
> MDL-86254: comment API

- docs/devupdate.md
[docs] Activity chooser update
> MDL-80295 documenting changes in the activity chooser.

- general/releases/4.5.md
- general/releases/5.0.md
- general/releases/5.1.md
- general/releases/5.2.md
- general/releases/5.3.md
Related to the patch on [MDL-85316](https://tracker.moodle.org/browse/MDL-85316).
[MDL-85316]: https://moodle.atlassian.net/browse/MDL-85316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MDL-85316 Adding Aurora MySQL version

- general/development/policies/accessibility.md
Updates to the accessibility policy page for the recent WCAG 2.2 Level AA accreditation for LMS and Workplace.
Also, fix the links to the accessibility conformance reports of LMS and Workplace to have unique accessible names to prevent screen reader users from seeing two different links with the same name on the page.
> Update accessibility policy for WCAG 2.2 accreditation

- data/versions.json
- general/releases.md
- general/releases/4.5/4.5.7.md
- general/releases/5.0/5.0.3.md
- general/releases/5.1.md
I've also included one additional line in the minor releases, where an issue should have been included but was initially missed.
This includes updating the messaging about the directory restructure to match the latest links and information being published across various forums etc, for consistency.
> 5.1 major release notes
